export type SiteSearchEntry = {
  id: string;
  title: string;
  description: string;
  path: string;
  group: "Pages" | "Forms" | "Anchors";
  keywords?: string[];
};

export const SITE_SEARCH_INDEX: SiteSearchEntry[] = [
  {
    id: "page-home",
    title: "Home",
    description: "Main landing page with featured products, company overview, and contact options.",
    path: "/",
    group: "Pages",
    keywords: ["hero", "about", "features", "contact", "welcome"],
  },
  {
    id: "page-knowledge",
    title: "Knowledge Base",
    description: "Articles, guides, and frequently asked questions for optical lenses and coatings.",
    path: "/knowledge",
    group: "Pages",
    keywords: ["faq", "articles", "learning resources"],
  },
  {
    id: "page-store",
    title: "Product Catalog",
    description: "Browse lenses and optical supplies.",
    path: "/store",
    group: "Pages",
    keywords: ["products", "lenses", "supplies", "catalog"],
  },
  {
    id: "page-professionals",
    title: "Professionals",
    description: "Resources and services for optical stores and clinics.",
    path: "/professionals",
    group: "Pages",
    keywords: ["wholesale", "partners", "trade"],
  },
  {
    id: "page-patients",
    title: "Patients",
    description: "Patient education and lens care information.",
    path: "/patients",
    group: "Pages",
    keywords: ["vision", "care", "guide"],
  },
  {
    id: "page-patients-lens-differences",
    title: "What's the Difference Between Lenses?",
    description: "Patient-friendly overview of single vision, progressive, and specialty lens choices.",
    path: "/patients/lens-differences",
    group: "Pages",
    keywords: ["patients", "lenses", "progressive", "single vision"],
  },
  {
    id: "page-patients-progressive-lenses",
    title: "Why Choose Progressive Lenses?",
    description: "When progressive lenses make sense and what to expect from them.",
    path: "/patients/progressive-lenses",
    group: "Pages",
    keywords: ["patients", "progressives", "multifocal"],
  },
  {
    id: "page-patients-anti-fatigue",
    title: "Eye Strain and Anti-Fatigue Lenses",
    description: "Screen-related visual fatigue guidance and anti-fatigue lens education.",
    path: "/patients/anti-fatigue-lenses",
    group: "Pages",
    keywords: ["patients", "digital eye strain", "anti-fatigue", "screens"],
  },
  {
    id: "page-patients-caring-for-glasses",
    title: "Caring for Your Glasses",
    description: "Cleaning and storage habits that protect lenses and coatings.",
    path: "/patients/caring-for-glasses",
    group: "Pages",
    keywords: ["patients", "lens care", "cleaning", "coatings"],
  },
  {
    id: "page-patients-computer-mobile-use",
    title: "Computer and Mobile Use",
    description: "Practical habits to reduce digital eye strain during screen-heavy routines.",
    path: "/patients/computer-mobile-use",
    group: "Pages",
    keywords: ["patients", "computer", "mobile", "screen use"],
  },
  {
    id: "page-patients-sunlight-protection",
    title: "Sunlight and Protection",
    description: "Outdoor comfort guidance covering UV protection and glare control.",
    path: "/patients/sunlight-protection",
    group: "Pages",
    keywords: ["patients", "sunlight", "UV", "polarized", "photochromic"],
  },
  {
    id: "page-patients-regular-eye-exams",
    title: "Regular Eye Exams",
    description: "Why routine eye exams matter for comfort, prescription accuracy, and health.",
    path: "/patients/regular-eye-exams",
    group: "Pages",
    keywords: ["patients", "eye exams", "prescription", "eye health"],
  },
  {
    id: "anchor-home-about",
    title: "About section",
    description: "Jump to company story, mission, and values.",
    path: "/#about",
    group: "Anchors",
    keywords: ["mission", "values", "story"],
  },
  {
    id: "anchor-home-contact",
    title: "Contact section",
    description: "Jump to contact and support section.",
    path: "/#contact",
    group: "Anchors",
    keywords: ["phone", "email", "support"],
  },
  {
    id: "anchor-patients-understanding",
    title: "Patients: Understanding lenses",
    description: "Educational lens overview for patients.",
    path: "/patients#understanding-lenses",
    group: "Anchors",
    keywords: ["progressive", "single vision", "anti-fatigue"],
  },
  {
    id: "anchor-patients-vision-tips",
    title: "Patients: Vision tips",
    description: "Overview section for patient vision habits and care reminders.",
    path: "/patients#vision-tips",
    group: "Anchors",
    keywords: ["patients", "screen use", "sunlight", "eye exams"],
  },
  {
    id: "anchor-patients-find-care",
    title: "Patients: Find care",
    description: "How to connect with a vision expert.",
    path: "/patients#find-care",
    group: "Anchors",
    keywords: ["optician", "clinic", "eye care"],
  },
  {
    id: "form-trade-account",
    title: "Apply for a Trade Account",
    description: "Professional onboarding form.",
    path: "/professionals/trade-account",
    group: "Forms",
    keywords: ["application", "onboarding", "professional form"],
  },
  {
    id: "form-price-list-request",
    title: "Price List Request",
    description: "Request wholesale pricing form.",
    path: "/professionals/price-list-request",
    group: "Forms",
    keywords: ["pricing", "request form", "wholesale"],
  },
];
