export type SiteSearchEntry = {
  id: string;
  title: string;
  description: string;
  path: string;
  group: "Pages" | "Forms" | "Anchors";
  keywords?: string[];
};

export const SITE_SEARCH_INDEX: SiteSearchEntry[] = [
  // ─── Core pages ──────────────────────────────────────────────────────────────
  {
    id: "page-home",
    title: "Home",
    description: "Main landing page with featured products, company overview, and contact options.",
    path: "/",
    group: "Pages",
    keywords: ["hero", "about", "features", "contact", "welcome", "classic visions"],
  },
  {
    id: "page-knowledge",
    title: "Knowledge Base",
    description: "Articles, guides, and frequently asked questions for optical lenses and coatings.",
    path: "/knowledge",
    group: "Pages",
    keywords: ["faq", "articles", "learning resources", "guides", "help"],
  },
  {
    id: "page-store",
    title: "Product Catalog",
    description: "Browse all lenses, coatings, and optical supplies available for order.",
    path: "/store",
    group: "Pages",
    keywords: ["products", "lenses", "supplies", "catalog", "shop", "order"],
  },
  {
    id: "page-professionals",
    title: "Professionals",
    description: "Resources and services for optical stores, clinics, and wholesale partners.",
    path: "/professionals",
    group: "Pages",
    keywords: ["wholesale", "partners", "trade", "optician", "clinic", "b2b", "professional"],
  },
  {
    id: "page-patients",
    title: "Patients",
    description: "Patient education, lens care information, and vision health guides.",
    path: "/patients",
    group: "Pages",
    keywords: ["vision", "care", "guide", "patient education", "eye health"],
  },

  // ─── Lens type pages ─────────────────────────────────────────────────────────
  {
    id: "page-lenses-hub",
    title: "Lens Types",
    description: "Overview of all lens categories: progressive, single vision, anti-fatigue, bifocals, and more.",
    path: "/lenses/lens-types",
    group: "Pages",
    keywords: [
      "lenses", "lens types", "progressive", "single vision", "anti-fatigue",
      "bifocals", "office lenses", "blue filter", "polarized", "photochromic",
      "myopia control", "materials", "tints",
    ],
  },
  {
    id: "page-lenses-progressive",
    title: "Progressive Lenses",
    description: "Personalized digital free-form progressive lenses. Seamless near-to-distance vision correction for presbyopia — no visible segment line.",
    path: "/lenses/progressive",
    group: "Pages",
    keywords: [
      "progressive lenses", "progressive", "multifocal", "presbyopia",
      "no-line bifocal", "varifocal", "distance near intermediate",
      "free-form", "digital progressive", "IOT", "Steady Methodology",
      "Endless Steady", "Essential Steady", "Classic", "Adapt",
      "reading and distance", "lens optimization", "personalized lenses",
      "accommodation", "age-related vision", "progressive corridor",
    ],
  },
  {
    id: "page-lenses-single-vision",
    title: "Single Vision Lenses",
    description: "Personalized free-form single vision lenses for distance, intermediate, or near correction — powered by IOT Digital Ray-Path 2.",
    path: "/lenses/single-vision",
    group: "Pages",
    keywords: [
      "single vision", "single vision lenses", "distance lenses",
      "reading glasses", "near vision", "myopia correction",
      "hyperopia correction", "Endless Single Vision", "IOT",
      "CR-39", "polycarbonate", "high index", "1.56", "1.60", "1.67", "1.74",
      "digital design", "ray-tracing", "prescription lenses",
    ],
  },
  {
    id: "page-lenses-anti-fatigue",
    title: "Anti-Fatigue Lenses",
    description: "Single-vision lenses with a power boost zone to combat digital eye strain and visual fatigue from screen use.",
    path: "/lenses/anti-fatigue",
    group: "Pages",
    keywords: [
      "anti-fatigue", "anti fatigue lenses", "digital eye strain", "screen fatigue",
      "computer vision", "near support", "power boost", "accommodation support",
      "screens", "computer glasses", "Endless Anti-Fatigue",
      "reading speed", "near-vision support", "presbyope",
      "Light Boost", "Medium Boost", "Full Boost", "0.50D", "0.75D", "1.00D",
    ],
  },
  {
    id: "page-lenses-bifocals",
    title: "Bifocal Lenses",
    description: "Conventional and digital freeform bifocals offering near and distance correction with or without a visible segment line.",
    path: "/lenses/bifocals",
    group: "Pages",
    keywords: [
      "bifocals", "bifocal lenses", "flat-top bifocal", "FT-28", "segment",
      "digital bifocal", "Endless Bifocal", "near distance vision",
      "reading segment", "two zone vision", "presbyopia", "multifocal",
      "freeform bifocal", "D-segment",
    ],
  },
  {
    id: "page-lenses-blue-filter",
    title: "Blue Filter Lenses",
    description: "Honest guide to blue light filtering — what blue filter lenses actually do, how they differ from blue-reflective coatings, and when they make sense.",
    path: "/lenses/blue-filter",
    group: "Pages",
    keywords: [
      "blue filter", "blue light filter", "blue light blocking", "blue lens",
      "HEV light", "short wavelength light", "screen protection",
      "digital eye strain", "blue-violet", "blue reflective",
      "blue light glasses", "computer glasses", "blue filter lens",
      "BV coating", "light filtering",
    ],
  },
  {
    id: "page-lenses-led-pro",
    title: "LED PRO Lenses",
    description: "Patented selective-filter lifestyle lenses designed for LED headlight glare, gaming, screens, and harsh indoor LED lighting.",
    path: "/lenses/led-pro",
    group: "Pages",
    keywords: [
      "led pro", "led lenses", "led glare", "headlight glare", "gaming lenses",
      "screen glare", "indoor led lighting", "450 nm", "550 nm", "selective absorption",
      "night driving", "younger optics", "led fatigue", "stadium lights",
    ],
  },
  {
    id: "page-lenses-polarized",
    title: "Polarized Lenses",
    description: "Polarized lenses cut reflected glare from roads, water, windshields, and sand — sharper, calmer outdoor vision in bright Caribbean conditions.",
    path: "/lenses/polarized",
    group: "Pages",
    keywords: [
      "polarized", "polarized lenses", "polarized sunglasses", "glare reduction",
      "anti-glare", "reflective glare", "driving glasses", "water glare",
      "fishing lenses", "boat lenses", "road glare", "polarization filter",
      "sun lens", "outdoor lenses", "tropical eyewear",
    ],
  },
  {
    id: "page-lenses-office-occupational",
    title: "Office & Occupational Lenses",
    description: "Personalized occupational lenses optimized for near and intermediate zones — ideal for office, computer, and workspace use.",
    path: "/lenses/office-occupational",
    group: "Pages",
    keywords: [
      "office lenses", "occupational lenses", "office glasses", "desk lenses",
      "computer glasses", "workspace vision", "intermediate vision",
      "near vision zones", "progressive alternative", "Desk Focus",
      "Workstation", "Room", "IOT", "workplace ergonomics",
      "computer monitor", "screen distance",
    ],
  },
  {
    id: "page-lenses-myopia-control",
    title: "Myopia Control",
    description: "Evidence-based guide to slowing myopia progression in children — spectacle lenses, contact lenses, ortho-k, and atropine explained.",
    path: "/lenses/myopia-control",
    group: "Pages",
    keywords: [
      "myopia control", "myopia management", "nearsightedness progression",
      "children myopia", "kids prescription", "axial elongation",
      "MiSight", "ortho-k", "orthokeratology", "atropine",
      "myopia spectacle", "myopia contact lens", "school-age myopia",
      "prescription increase", "shortsighted child",
    ],
  },
  {
    id: "page-lenses-materials",
    title: "Lens Materials",
    description: "Compare CR-39, polycarbonate, Trivex, and high-index materials by refractive index, weight, thickness, and impact resistance.",
    path: "/lenses/materials",
    group: "Pages",
    keywords: [
      "lens materials", "CR-39", "polycarbonate", "Trivex",
      "high index", "1.50", "1.56", "1.59", "1.60", "1.67", "1.74",
      "MR-8", "MR-7", "MR-174", "lens thickness", "lens weight",
      "refractive index", "Abbe value", "impact resistance", "thin lenses",
      "lightweight lenses", "material comparison",
    ],
  },
  {
    id: "page-lenses-tints",
    title: "Tints & Fashion Colors",
    description: "Lens tint options for sun protection and fashion — solid and gradient tints in gray, brown, G-15, blue, rose, copper, and more.",
    path: "/lenses/tints-fashion-colors",
    group: "Pages",
    keywords: [
      "tinted lenses", "lens tints", "fashion colors", "sunwear", "gradient tints",
      "lens color", "sun tint", "Classic Gray", "Warm Brown", "G-15",
      "Fashion Rose", "Ocean Blue", "Sunset Copper", "Graphite Smoke",
      "Bronze Gold", "Tea Amber", "Olive Field", "Violet Plum", "Ruby Red",
      "gradient", "solid tint", "transmission density", "cosmetic tint",
    ],
  },
  {
    id: "page-lenses-thickness-chart",
    title: "Lens Thickness Chart",
    description: "Edge and center thickness reference for minus and plus prescriptions across materials — helps match frame choice to prescription strength.",
    path: "/lenses/thickness-chart",
    group: "Pages",
    keywords: [
      "thickness chart", "lens thickness", "edge thickness", "center thickness",
      "thick lenses", "thin lenses", "blank diameter", "minus lens",
      "plus lens", "prescription strength", "frame size", "material index",
      "minimum blank size", "MBS", "cosmetic appearance",
    ],
  },

  // ─── Photochromic ─────────────────────────────────────────────────────────────
  {
    id: "page-photochromic",
    title: "Photochromic Lenses Guide",
    description: "Complete guide to light-reactive lenses — Darkun house brand and Transitions families, with performance levels, colors, and driving suitability explained.",
    path: "/photochromic",
    group: "Pages",
    keywords: [
      "photochromic", "photochromic lenses", "light reactive lenses",
      "adaptive lenses", "Transitions", "Transitions GEN S", "XTRActive",
      "Drivewear", "Darkun", "light sensitive", "UV activation",
      "indoor outdoor lenses", "auto-tint", "darkening lenses",
      "driving photochromic", "fast fade", "color photochromic",
      "Gray", "Brown", "Graphite Green", "Amethyst", "Amber", "Emerald",
    ],
  },

  // ─── Coating pages ────────────────────────────────────────────────────────────
  {
    id: "page-coatings-ultraclear-ar",
    title: "Super AR — Anti-Reflective Coating",
    description: "Premium multi-layer anti-reflective coating that virtually eliminates glare, improves cosmetic clarity, and enhances night-driving comfort.",
    path: "/coatings/ultraclear-ar",
    group: "Pages",
    keywords: [
      "anti-reflective", "anti-reflective coating", "AR coating", "Super AR",
      "Super AR", "glare reduction", "night driving", "reflections",
      "lens clarity", "multi-layer AR", "hydrophobic top coat",
      "oleophobic", "premium coating", "cosmetic appearance",
      "reduce glare", "AR lens",
    ],
  },
  {
    id: "page-coatings-blueblock-ar",
    title: "Blue Defense AR+ — Blue Light AR Coating",
    description: "Anti-reflective coating with selective blue-violet light filtering — reduces screen glare while preserving natural color balance for everyday wear.",
    path: "/coatings/blueblock-ar",
    group: "Pages",
    keywords: [
      "blue light coating", "Blue Defense AR+", "BlueBlock AR",
      "blue filter coating", "blue AR", "anti-reflective blue",
      "screen glare", "digital eye strain coating", "blue-violet",
      "computer glasses coating", "LED protection", "office coating",
    ],
  },
  {
    id: "page-coatings-scratch-resistant",
    title: "Scratch-Resistant Coating",
    description: "Hard coat foundation layer that protects lens surfaces from micro-scratches caused by routine cleaning, handling, and everyday wear.",
    path: "/coatings/scratch-resistant",
    group: "Pages",
    keywords: [
      "scratch resistant", "scratch-resistant coating", "hard coat",
      "scratch protection", "lens durability", "micro-scratches",
      "surface protection", "lens care", "coating foundation",
      "everyday lens protection", "lens longevity",
    ],
  },
  {
    id: "page-coatings-uv-shield",
    title: "UV Shield Coating",
    description: "UVA, UVB, and blue-violet blocking coating for broad-spectrum light protection — effective even on clear lenses and on cloudy days.",
    path: "/coatings/uv-shield",
    group: "Pages",
    keywords: [
      "UV protection", "UV shield", "UVA UVB", "UV coating",
      "ultraviolet", "eye protection", "sun protection",
      "blue-violet protection", "BV coating", "clear lens UV",
      "outdoor protection", "tropical UV", "UV blocking",
    ],
  },
  {
    id: "page-coatings-mirror",
    title: "Mirror Coatings & Finish Guide",
    description: "Reflective mirror top layers for tinted and sun lenses — available in Silver Flash, Blue Ice, Rose Gold, Emerald Green, and more.",
    path: "/coatings/mirror",
    group: "Pages",
    keywords: [
      "mirror coating", "mirror finish", "reflective coating",
      "sunglass coating", "Silver Flash", "Blue Ice", "Rose Gold",
      "Emerald Green", "Sunset Copper", "Violet Chrome",
      "flash mirror", "sport sunglasses", "fashion eyewear", "mirror lens",
    ],
  },
  {
    id: "page-coatings-hydrophobic-oleophobic",
    title: "Hydrophobic & Oleophobic Top Coats",
    description: "Water and oil repellent finishing layers that resist fingerprints, smudges, and moisture — keeping lenses cleaner between wipes.",
    path: "/coatings/hydrophobic-oleophobic",
    group: "Pages",
    keywords: [
      "hydrophobic", "oleophobic", "water repellent", "smudge resistant",
      "fingerprint resistance", "oil repellent", "lens cleaning",
      "self-cleaning lens", "nano coating", "top coat",
      "tropical humidity", "easy clean", "maintenance coating",
    ],
  },

  // ─── Patient education sub-pages ──────────────────────────────────────────────
  {
    id: "page-patients-lens-differences",
    title: "What's the Difference Between Lenses?",
    description: "Patient-friendly overview of single vision, progressive, and specialty lens choices.",
    path: "/patients/lens-differences",
    group: "Pages",
    keywords: ["patients", "lenses", "progressive", "single vision", "lens comparison", "which lens"],
  },
  {
    id: "page-patients-progressive-lenses",
    title: "Why Choose Progressive Lenses? (Patient Guide)",
    description: "When progressive lenses make sense and what to expect from them — written for patients.",
    path: "/patients/progressive-lenses",
    group: "Pages",
    keywords: ["patients", "progressives", "multifocal", "varifocal", "no-line", "presbyopia guide"],
  },
  {
    id: "page-patients-anti-fatigue",
    title: "Eye Strain and Anti-Fatigue Lenses",
    description: "Screen-related visual fatigue guidance and anti-fatigue lens education for patients.",
    path: "/patients/anti-fatigue-lenses",
    group: "Pages",
    keywords: ["patients", "digital eye strain", "anti-fatigue", "screens", "computer eye strain", "tired eyes"],
  },
  {
    id: "page-patients-caring-for-glasses",
    title: "Caring for Your Glasses",
    description: "Cleaning and storage habits that protect lenses and coatings.",
    path: "/patients/caring-for-glasses",
    group: "Pages",
    keywords: ["patients", "lens care", "cleaning", "coatings", "glasses care", "microfibre"],
  },
  {
    id: "page-patients-computer-mobile-use",
    title: "Computer and Mobile Use",
    description: "Practical habits to reduce digital eye strain during screen-heavy routines.",
    path: "/patients/computer-mobile-use",
    group: "Pages",
    keywords: ["patients", "computer", "mobile", "screen use", "20-20-20", "device eye strain"],
  },
  {
    id: "page-patients-sunlight-protection",
    title: "Sunlight and Protection",
    description: "Outdoor comfort guidance covering UV protection and glare control.",
    path: "/patients/sunlight-protection",
    group: "Pages",
    keywords: ["patients", "sunlight", "UV", "polarized", "photochromic", "outdoor protection"],
  },
  {
    id: "page-patients-regular-eye-exams",
    title: "Regular Eye Exams",
    description: "Why routine eye exams matter for comfort, prescription accuracy, and health.",
    path: "/patients/regular-eye-exams",
    group: "Pages",
    keywords: ["patients", "eye exams", "prescription", "eye health", "annual checkup", "optometrist"],
  },

  // ─── Anchors ─────────────────────────────────────────────────────────────────
  {
    id: "anchor-home-about",
    title: "About section",
    description: "Jump to company story, mission, and values.",
    path: "/#about",
    group: "Anchors",
    keywords: ["mission", "values", "story", "about us"],
  },
  {
    id: "anchor-home-contact",
    title: "Contact section",
    description: "Jump to contact and support section.",
    path: "/#contact",
    group: "Anchors",
    keywords: ["phone", "email", "support", "contact us"],
  },
  {
    id: "anchor-patients-understanding",
    title: "Patients: Understanding lenses",
    description: "Educational lens overview for patients.",
    path: "/patients#understanding-lenses",
    group: "Anchors",
    keywords: ["progressive", "single vision", "anti-fatigue", "lens overview"],
  },
  {
    id: "anchor-patients-vision-tips",
    title: "Patients: Vision tips",
    description: "Overview section for patient vision habits and care reminders.",
    path: "/patients#vision-tips",
    group: "Anchors",
    keywords: ["patients", "screen use", "sunlight", "eye exams", "vision habits"],
  },
  {
    id: "anchor-patients-find-care",
    title: "Patients: Find care",
    description: "How to connect with a vision expert.",
    path: "/patients#find-care",
    group: "Anchors",
    keywords: ["optician", "clinic", "eye care", "find optician"],
  },

  // ─── Forms ───────────────────────────────────────────────────────────────────
  {
    id: "form-trade-account",
    title: "Apply for a Trade Account",
    description: "Professional onboarding form for optical stores and clinics.",
    path: "/professionals/trade-account",
    group: "Forms",
    keywords: ["application", "onboarding", "professional form", "trade account", "wholesale account"],
  },
  {
    id: "form-price-list-request",
    title: "Price List Request",
    description: "Request wholesale pricing form for professionals.",
    path: "/professionals/price-list-request",
    group: "Forms",
    keywords: ["pricing", "request form", "wholesale", "price list", "wholesale pricing"],
  },
];
