project_id = "xstmeirxhfbiyayrrsob"

[functions]
  [functions.admin-user-management]
    verify_jwt = false
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.lens-assistant]
    verify_jwt = false
