import js from "@eslint/js";
import globals from "globals";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import tseslint from "typescript-eslint";

export default tseslint.config(
  {
    // supabase/functions/mcp/index.ts is auto-generated by @lovable.dev/mcp-js
    // from src/lib/mcp/** and gets overwritten on every regeneration — linting
    // its `var` output would just fail again next time the plugin runs.
    ignores: ["dist", "coverage", ".claude", "public/ds/vendor/**", "supabase/functions/mcp/index.ts"],
  },
  {
    extends: [js.configs.recommended, ...tseslint.configs.recommended],
    files: ["**/*.{ts,tsx}"],
    languageOptions: {
      ecmaVersion: 2020,
      globals: globals.browser,
    },
    plugins: {
      "react-hooks": reactHooks,
      "react-refresh": reactRefresh,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      // eslint-plugin-react-hooks v7 enables React Compiler diagnostics that
      // flag established patterns across the app. Keep them visible while
      // migrating incrementally instead of turning the dependency update into
      // a repo-wide behavioral rewrite.
      "react-hooks/set-state-in-effect": "warn",
      "react-hooks/static-components": "warn",
      "react-hooks/purity": "warn",
      "react-hooks/refs": "warn",
      "react-hooks/preserve-manual-memoization": "warn",
      "react-hooks/immutability": "warn",
      "react-refresh/only-export-components": ["warn", { allowConstantExport: true }],
      "@typescript-eslint/no-unused-vars": "off",
      "@typescript-eslint/no-explicit-any": "warn",
      "@typescript-eslint/no-unused-expressions": "warn",
      "@typescript-eslint/no-require-imports": "warn",
      "prefer-const": "warn",
      "no-useless-escape": "warn",
      "no-useless-assignment": "warn",
      "no-restricted-syntax": [
        "error",
        {
          selector: "JSXAttribute[name.name='dangerouslySetInnerHTML']",
          message: "Use approved sanitizer/trusted wrapper components instead of direct dangerouslySetInnerHTML.",
        },
      ],
    },
  },
);
