// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-nocheck
// AUTO-GENERATED by scripts/generate_mcp_function.mjs — do not edit.
// Regenerate only with npm run mcp:generate before deploying the MCP function.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/tools/whoami.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.110.7";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv(["SUPABASE_PUBLISHABLE_KEY", "VITE_SUPABASE_PUBLISHABLE_KEY"]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
      // Intentionally swallowed — parse failure means this key source is unavailable
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
async function currentUserId(ctx) {
  const { data } = await supabaseForUser(ctx).auth.getUser();
  return data?.user?.id;
}
const notAuthenticated = {
  content: [{ type: "text", text: "Not authenticated." }],
  isError: true
};
function ok(payload, structured) {
  return {
    content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
    structuredContent: structured ?? { result: payload }
  };
}
function fail(message) {
  return { content: [{ type: "text", text: message }], isError: true };
}
function likePattern(query) {
  return `%${query.replace(/[%_]/g, "")}%`;
}
async function callPortalCopilot(ctx, body) {
  const token = ctx.getToken();
  if (!token) throw new Error("callPortalCopilot requires a verified OAuth token");
  const response = await fetch(`${supabaseProjectUrl()}/functions/v1/portal-copilot`, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${token}`,
      apikey: supabasePublishableKey(),
      "Content-Type": "application/json"
    },
    body: JSON.stringify(body)
  });
  const payload = await response.json().catch(() => ({}));
  if (!response.ok) {
    throw new Error(typeof payload?.error === "string" ? payload.error : `Portal Copilot failed (${response.status})`);
  }
  return payload;
}

// src/lib/mcp/tools/whoami.ts
const whoami_default = defineTool({
  name: "whoami",
  title: "Who am I",
  description: "Return the signed-in Classic Visions user's id, email, roles, portal profile and linked customer accounts. Call this first to understand what the caller can access.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated;
    const supabase = supabaseForUser(ctx);
    const userId = ctx.getUserId();
    const [{ data: roles }, { data: profile }, { data: memberships }] = await Promise.all([
      supabase.from("user_roles").select("role").eq("user_id", userId),
      supabase.from("profiles").select("full_name,display_name,organization_name,portal_access_status,crm_customer_id,crm_contact_id,email").eq("user_id", userId).maybeSingle(),
      supabase.rpc("get_portal_account_memberships").then((r) => r, () => ({ data: null }))
    ]);
    const summary = {
      user_id: userId,
      email: ctx.getUserEmail(),
      roles: (roles ?? []).map((r) => r.role),
      profile: profile ?? null,
      accounts: memberships ?? null
    };
    return ok(summary, summary);
  }
});

// src/lib/mcp/tools/search-products.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z } from "npm:zod@^4.4.3";
const matches = (row, needle) => String(row.name ?? "").toLowerCase().includes(needle) || String(row.description ?? "").toLowerCase().includes(needle) || String(row.sku ?? "").toLowerCase().includes(needle);
const search_products_default = defineTool2({
  name: "search_products",
  title: "Search catalog",
  description: "Search the Classic Visions catalog (lenses, supplies, add-ons) by name, SKU or description. Cost data is never returned.",
  inputSchema: {
    query: z.string().min(1).describe("Search text matched against name, SKU or description."),
    category: z.enum(["all", "lenses", "supplies", "addons"]).optional().describe("Restrict the search to one catalog type (default: all)."),
    limit: z.number().int().min(1).max(50).optional().describe("Max rows per category (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, category, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated;
    const supabase = supabaseForUser(ctx);
    const cap = limit ?? 10;
    const needle = query.toLowerCase();
    const want = category ?? "all";
    const load = async (rpc) => {
      const { data, error } = await supabase.rpc(rpc);
      if (error) throw new Error(`${rpc}: ${error.message}`);
      return (data ?? []).filter((r) => matches(r, needle)).slice(0, cap);
    };
    try {
      const [lenses, supplies, addons] = await Promise.all([
        want === "all" || want === "lenses" ? load("get_lenses_safe") : Promise.resolve([]),
        want === "all" || want === "supplies" ? load("get_supplies_safe") : Promise.resolve([]),
        want === "all" || want === "addons" ? load("get_addons_safe") : Promise.resolve([])
      ]);
      const payload = { lenses, supplies, addons };
      return ok(payload, { count: lenses.length + supplies.length + addons.length, ...payload });
    } catch (err) {
      return fail(err instanceof Error ? err.message : "Catalog search failed.");
    }
  }
});

// src/lib/mcp/tools/list-my-orders.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z2 } from "npm:zod@^4.4.3";
const list_my_orders_default = defineTool3({
  name: "list_orders",
  title: "List orders",
  description: "List Classic Visions orders visible to the signed-in user (most recent first). RLS limits customers to their own orders; staff see all.",
  inputSchema: {
    status: z2.string().min(1).optional().describe("Filter by order status (e.g. pending, paid, cancelled)."),
    limit: z2.number().int().min(1).max(50).optional().describe("Max orders to return (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated;
    const supabase = supabaseForUser(ctx);
    let q = supabase.from("orders").select("id,status,total_amount,customer_name,contact_email,checkout_method,created_at,updated_at").order("created_at", { ascending: false }).limit(limit ?? 10);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return fail(error.message);
    const rows = data ?? [];
    return ok(rows, { count: rows.length, orders: rows });
  }
});

// src/lib/mcp/tools/get-order.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z3 } from "npm:zod@^4.4.3";
const get_order_default = defineTool4({
  name: "get_order",
  title: "Get order details",
  description: "Fetch one order with its line items, payments and activity. RLS restricts access to orders the caller may see.",
  inputSchema: { order_id: z3.string().min(1).describe("Order id returned by list_orders.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ order_id }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated;
    const supabase = supabaseForUser(ctx);
    const { data: order, error } = await supabase.from("orders").select("id,status,total_amount,customer_name,contact_email,contact_phone,shipping_address,billing_address,checkout_method,created_at,updated_at").eq("id", order_id).maybeSingle();
    if (error) return fail(error.message);
    if (!order) return fail("Order not found or not visible to this user.");
    const [{ data: items }, { data: payments }] = await Promise.all([
      supabase.from("order_items").select("id,product_name,product_type,variant_label,sku,opc_code,quantity,product_price,unit_price_snapshot").eq("order_id", order_id),
      supabase.from("order_payments").select("id,status,amount,currency,method,created_at").eq("order_id", order_id).then((r) => r, () => ({ data: null }))
    ]);
    const payload = { order, items: items ?? [], payments: payments ?? [] };
    return ok(payload, payload);
  }
});

// src/lib/mcp/tools/list-statements.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z4 } from "npm:zod@^4.4.3";
const list_statements_default = defineTool5({
  name: "list_statements",
  title: "List account statements",
  description: "List billing statements visible to the caller (most recent first), optionally for one customer account number.",
  inputSchema: {
    account_number: z4.string().min(1).optional().describe("Filter by customer account number."),
    limit: z4.number().int().min(1).max(50).optional().describe("Max statements to return (default 12).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ account_number, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated;
    const supabase = supabaseForUser(ctx);
    let q = supabase.from("statements").select("id,account_number,statement_date,from_date,to_date,due_date,opening_balance,closing_balance,payments,finance_charges,status").order("statement_date", { ascending: false }).limit(limit ?? 12);
    if (account_number) q = q.eq("account_number", account_number);
    const { data, error } = await q;
    if (error) return fail(error.message);
    const rows = data ?? [];
    return ok(rows, { count: rows.length, statements: rows });
  }
});

// src/lib/mcp/tools/get-statement.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z5 } from "npm:zod@^4.4.3";
const get_statement_default = defineTool6({
  name: "get_statement",
  title: "Get statement transactions",
  description: "Fetch one statement with its transaction lines (invoices, payments, credits).",
  inputSchema: {
    statement_id: z5.string().min(1).describe("Statement id returned by list_statements."),
    limit: z5.number().int().min(1).max(500).optional().describe("Max transaction lines (default 200).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ statement_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated;
    const supabase = supabaseForUser(ctx);
    const { data: statement, error } = await supabase.from("statements").select("id,innovations_statement_id,account_number,statement_date,from_date,to_date,due_date,opening_balance,closing_balance,payments,finance_charges,status").eq("id", statement_id).maybeSingle();
    if (error) return fail(error.message);
    if (!statement) return fail("Statement not found or not visible to this user.");
    const { data: lines, error: lineError } = await supabase.from("statement_lines").select("id,post_date,order_type_name,invoice_id,reference,patient,amount,payment_method").eq("innovations_statement_id", statement.innovations_statement_id).order("post_date", { ascending: true }).limit(limit ?? 200);
    if (lineError) return fail(lineError.message);
    const payload = { statement, lines: lines ?? [] };
    return ok(payload, payload);
  }
});

// src/lib/mcp/tools/get-account-balance.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z6 } from "npm:zod@^4.4.3";
const get_account_balance_default = defineTool7({
  name: "get_account_balance",
  title: "Get account balance",
  description: "Return current balance, credit limit and last statement/payment info for the caller's customer account(s).",
  inputSchema: {
    account_number: z6.string().min(1).optional().describe("Limit to one customer account number.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ account_number }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated;
    const supabase = supabaseForUser(ctx);
    let q = supabase.from("balances").select("account_number,credit_limit,current_balance,last_statement_amount,last_statement_date,last_payment_amount,last_payment_date,synced_at").limit(25);
    if (account_number) q = q.eq("account_number", account_number);
    const { data, error } = await q;
    if (error) return fail(error.message);
    const rows = data ?? [];
    return ok(rows, { count: rows.length, balances: rows });
  }
});

// src/lib/mcp/tools/list-quotes.ts
import { defineTool as defineTool8 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z7 } from "npm:zod@^4.4.3";
const list_quotes_default = defineTool8({
  name: "list_quotes",
  title: "List quotes",
  description: "List quotes visible to the caller (most recent first). Cost and margin fields are hidden from customers by policy.",
  inputSchema: {
    status: z7.string().min(1).optional().describe("Filter by quote status."),
    limit: z7.number().int().min(1).max(50).optional().describe("Max quotes to return (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated;
    const supabase = supabaseForUser(ctx);
    let q = supabase.from("quotes").select("id,quote_number,quote_type,status,customer_name,contact_name,contact_email,currency,valid_until,lead_time_days,grand_total,created_at").order("created_at", { ascending: false }).limit(limit ?? 10);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return fail(error.message);
    const rows = data ?? [];
    return ok(rows, { count: rows.length, quotes: rows });
  }
});

// src/lib/mcp/tools/get-quote.ts
import { defineTool as defineTool9 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z8 } from "npm:zod@^4.4.3";
const get_quote_default = defineTool9({
  name: "get_quote",
  title: "Get quote details",
  description: "Fetch one quote with its lines. Lines are read through the cost-safe server function, so customers never receive cost or margin data.",
  inputSchema: { quote_id: z8.string().min(1).describe("Quote id returned by list_quotes.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ quote_id }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated;
    const supabase = supabaseForUser(ctx);
    const { data: quote, error } = await supabase.from("quotes").select("id,quote_number,quote_type,status,customer_name,contact_name,contact_email,currency,valid_until,lead_time_days,notes_customer,grand_total,created_at").eq("id", quote_id).maybeSingle();
    if (error) return fail(error.message);
    if (!quote) return fail("Quote not found or not visible to this user.");
    const { data: lines, error: lineError } = await supabase.rpc("get_customer_quote_lines", { p_quote_id: quote_id });
    if (lineError) return fail(lineError.message);
    const payload = { quote, lines: lines ?? [] };
    return ok(payload, payload);
  }
});

// src/lib/mcp/tools/list-support-tickets.ts
import { defineTool as defineTool10 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z9 } from "npm:zod@^4.4.3";
const list_support_tickets_default = defineTool10({
  name: "list_support_tickets",
  title: "List support tickets",
  description: "List helpdesk tickets visible to the caller (most recent first).",
  inputSchema: {
    search: z9.string().min(1).optional().describe("Match against ticket title or description."),
    limit: z9.number().int().min(1).max(50).optional().describe("Max tickets to return (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated;
    const supabase = supabaseForUser(ctx);
    let q = supabase.from("helpdesk_tickets").select("id,ticket_number,title,description,priority,source_channel,customer_email,opened_at,closed_at,deadline,created_at").order("created_at", { ascending: false }).limit(limit ?? 10);
    if (search) {
      const like = `%${search.replace(/[%_]/g, "")}%`;
      q = q.or(`title.ilike.${like},description.ilike.${like}`);
    }
    const { data, error } = await q;
    if (error) return fail(error.message);
    const rows = data ?? [];
    return ok(rows, { count: rows.length, tickets: rows });
  }
});

// src/lib/mcp/tools/get-support-ticket.ts
import { defineTool as defineTool11 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z10 } from "npm:zod@^4.4.3";
const get_support_ticket_default = defineTool11({
  name: "get_support_ticket",
  title: "Get support ticket",
  description: "Fetch one helpdesk ticket with its message thread.",
  inputSchema: {
    ticket_id: z10.string().min(1).describe("Ticket id returned by list_support_tickets.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ ticket_id }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated;
    const supabase = supabaseForUser(ctx);
    const { data: ticket, error } = await supabase.from("helpdesk_tickets").select("id,ticket_number,title,description,priority,source_channel,customer_email,opened_at,first_response_at,closed_at,deadline,created_at,updated_at").eq("id", ticket_id).maybeSingle();
    if (error) return fail(error.message);
    if (!ticket) return fail("Ticket not found or not visible to this user.");
    const { data: messages, error: msgError } = await supabase.from("helpdesk_ticket_messages").select("id,direction,body,sender_name,sender_email,is_automated,sent_at,created_at").eq("ticket_id", ticket_id).order("created_at", { ascending: true }).limit(200);
    if (msgError) return fail(msgError.message);
    const payload = { ticket, messages: messages ?? [] };
    return ok(payload, payload);
  }
});

// src/lib/mcp/tools/create-support-ticket.ts
import { defineTool as defineTool12 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z11 } from "npm:zod@^4.4.3";
const create_support_ticket_default = defineTool12({
  name: "create_support_ticket",
  title: "Create support ticket",
  description: "Open a new Classic Visions helpdesk ticket on behalf of the signed-in user. Use only when the user explicitly asks for support.",
  inputSchema: {
    title: z11.string().trim().min(3).max(200).describe("Short subject line for the ticket."),
    description: z11.string().trim().min(3).max(5e3).describe("Full description of the issue or request."),
    priority: z11.string().min(1).optional().describe("Optional priority label recognised by the helpdesk.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async ({ title, description, priority }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated;
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("helpdesk_tickets").insert({
      title,
      description,
      ...priority ? { priority } : {},
      source_channel: "mcp",
      customer_email: ctx.getUserEmail() ?? null,
      owner_user_id: null
    }).select("id,ticket_number,title,priority,created_at").maybeSingle();
    if (error) return fail(error.message);
    return ok(data, { ticket: data });
  }
});

// src/lib/mcp/tools/reply-to-support-ticket.ts
import { defineTool as defineTool13 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z12 } from "npm:zod@^4.4.3";
const reply_to_support_ticket_default = defineTool13({
  name: "reply_to_support_ticket",
  title: "Reply to support ticket",
  description: "Append a message from the signed-in user to an existing helpdesk ticket thread.",
  inputSchema: {
    ticket_id: z12.string().min(1).describe("Ticket id returned by list_support_tickets."),
    body: z12.string().trim().min(1).max(5e3).describe("Message text to append.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async ({ ticket_id, body }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated;
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("helpdesk_ticket_messages").insert({
      ticket_id,
      body,
      direction: "inbound",
      sender_user_id: ctx.getUserId(),
      sender_email: ctx.getUserEmail() ?? null,
      is_automated: false
    }).select("id,ticket_id,created_at").maybeSingle();
    if (error) return fail(error.message);
    return ok(data, { message: data });
  }
});

// src/lib/mcp/tools/search-knowledge-base.ts
import { defineTool as defineTool14 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z13 } from "npm:zod@^4.4.3";
const search_knowledge_base_default = defineTool14({
  name: "search_knowledge_base",
  title: "Search help articles",
  description: "Search Classic Visions help/wiki articles by title, summary or body. Visibility rules limit results to what the caller may read.",
  inputSchema: {
    query: z13.string().min(1).describe("Search text."),
    limit: z13.number().int().min(1).max(25).optional().describe("Max articles to return (default 8).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated;
    const supabase = supabaseForUser(ctx);
    const like = likePattern(query);
    const { data, error } = await supabase.from("help_articles").select("id,title,slug,summary,description,category,content_type,page_slug,status,updated_at,content").or(`title.ilike.${like},summary.ilike.${like},description.ilike.${like},content.ilike.${like}`).limit(limit ?? 8);
    if (error) return fail(error.message);
    const rows = (data ?? []).map((row) => ({
      ...row,
      content: typeof row.content === "string" ? row.content.slice(0, 4e3) : row.content
    }));
    return ok(rows, { count: rows.length, articles: rows });
  }
});

// src/lib/mcp/tools/search-crm.ts
import { defineTool as defineTool15 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z14 } from "npm:zod@^4.4.3";
const search_crm_default = defineTool15({
  name: "search_crm",
  title: "Search CRM contacts and customers",
  description: "Search CRM contacts and customer accounts by name, email or account number. Staff-only in practice: RLS returns nothing for customer-role callers.",
  inputSchema: {
    query: z14.string().min(1).describe("Name, email, business name or account number."),
    limit: z14.number().int().min(1).max(25).optional().describe("Max rows per collection (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated;
    const supabase = supabaseForUser(ctx);
    const like = likePattern(query);
    const cap = limit ?? 10;
    const [contactsRes, customersRes] = await Promise.all([
      supabase.from("contacts").select("id,name,business_name,email,phone,city,country,pipeline,stage,status,is_customer,linked_customer_id,next_action_at").or(`name.ilike.${like},business_name.ilike.${like},email.ilike.${like}`).limit(cap),
      supabase.from("customers").select("id,name,account_number,type,email,phone,country_code,pipeline_stage,credit_limit,pay_by_card,pay_by_eft,assigned_pricelist_id").or(`name.ilike.${like},account_number.ilike.${like},email.ilike.${like}`).limit(cap)
    ]);
    if (contactsRes.error && customersRes.error) return fail(contactsRes.error.message);
    const payload = { contacts: contactsRes.data ?? [], customers: customersRes.data ?? [] };
    return ok(payload, payload);
  }
});

// src/lib/mcp/tools/list-crm-tasks.ts
import { defineTool as defineTool16 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z15 } from "npm:zod@^4.4.3";
const list_crm_tasks_default = defineTool16({
  name: "list_crm_tasks",
  title: "List CRM tasks and activities",
  description: "List CRM activities/tasks visible to the caller, newest first. Optionally filter to open tasks or one contact.",
  inputSchema: {
    contact_id: z15.string().min(1).optional().describe("Restrict to one CRM contact id."),
    status: z15.string().min(1).optional().describe("Filter by activity status (e.g. open, done)."),
    limit: z15.number().int().min(1).max(50).optional().describe("Max rows (default 15).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ contact_id, status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated;
    const supabase = supabaseForUser(ctx);
    let q = supabase.from("activities").select("id,contact_id,opportunity_id,type,activity_type,content,status,priority,due_at,completed_at,owner_id,task_channel,created_at").order("created_at", { ascending: false }).limit(limit ?? 15);
    if (contact_id) q = q.eq("contact_id", contact_id);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return fail(error.message);
    const rows = data ?? [];
    return ok(rows, { count: rows.length, activities: rows });
  }
});

// src/lib/mcp/tools/create-crm-task.ts
import { defineTool as defineTool17 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z16 } from "npm:zod@^4.4.3";
const create_crm_task_default = defineTool17({
  name: "create_crm_task",
  title: "Create a CRM task or note",
  description: "Log a CRM activity (note or task) against a contact. Staff-only in practice: RLS rejects callers without CRM write access.",
  inputSchema: {
    contact_id: z16.string().min(1).describe("CRM contact id from search_crm."),
    content: z16.string().trim().min(1).max(4e3).describe("Note text or task description."),
    activity_type: z16.string().min(1).optional().describe("Activity type label (e.g. note, call, email, task)."),
    due_at: z16.string().min(1).optional().describe("ISO timestamp when the task is due."),
    priority: z16.string().min(1).optional().describe("Priority label.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async ({ contact_id, content, activity_type, due_at, priority }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated;
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("activities").insert({
      contact_id,
      content,
      type: activity_type ?? "note",
      activity_type: activity_type ?? "note",
      created_by: ctx.getUserId(),
      owner_id: ctx.getUserId(),
      ...due_at ? { due_at, status: "open" } : {},
      ...priority ? { priority } : {}
    }).select("id,contact_id,activity_type,status,due_at,created_at").maybeSingle();
    if (error) return fail(error.message);
    return ok(data, { activity: data });
  }
});

// src/lib/mcp/tools/list-opportunities.ts
import { defineTool as defineTool18 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z17 } from "npm:zod@^4.4.3";
const list_opportunities_default = defineTool18({
  name: "list_opportunities",
  title: "List sales opportunities",
  description: "List CRM opportunities visible to the caller, newest first.",
  inputSchema: {
    stage: z17.string().min(1).optional().describe("Filter by pipeline stage."),
    limit: z17.number().int().min(1).max(50).optional().describe("Max rows (default 15).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ stage, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated;
    const supabase = supabaseForUser(ctx);
    let q = supabase.from("opportunities").select("id,title,contact_id,status,stage,country,volume_tier,expected_value,estimated_value,close_date,source,created_at").order("created_at", { ascending: false }).limit(limit ?? 15);
    if (stage) q = q.eq("stage", stage);
    const { data, error } = await q;
    if (error) return fail(error.message);
    const rows = data ?? [];
    return ok(rows, { count: rows.length, opportunities: rows });
  }
});

// src/lib/mcp/tools/list-pricelists.ts
import { defineTool as defineTool19 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z18 } from "npm:zod@^4.4.3";
const list_pricelists_default = defineTool19({
  name: "list_pricelists",
  title: "List pricelists and catalogs",
  description: "List pricelist versions and catalog templates the caller may see, to identify which pricelist applies to an account.",
  inputSchema: {
    limit: z18.number().int().min(1).max(50).optional().describe("Max rows per collection (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated;
    const supabase = supabaseForUser(ctx);
    const cap = limit ?? 20;
    const [versions, templates] = await Promise.all([
      supabase.from("pricelist_versions").select("id,name,base_currency,is_template,format_type,updated_at").order("updated_at", { ascending: false }).limit(cap),
      supabase.from("catalog_templates").select("id,name,status,cover_title,cover_subtitle,updated_at").order("updated_at", { ascending: false }).limit(cap)
    ]);
    if (versions.error && templates.error) return fail(versions.error.message);
    const payload = { pricelist_versions: versions.data ?? [], catalog_templates: templates.data ?? [] };
    return ok(payload, payload);
  }
});

// src/lib/mcp/tools/list-shipments.ts
import { defineTool as defineTool20 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z19 } from "npm:zod@^4.4.3";
const list_shipments_default = defineTool20({
  name: "list_shipments",
  title: "List inbound shipments",
  description: "List supplier shipments visible to the caller (most recent first). Staff-only in practice under RLS.",
  inputSchema: {
    status: z19.string().min(1).optional().describe("Filter by shipment status (draft, reviewed, locked)."),
    limit: z19.number().int().min(1).max(50).optional().describe("Max rows (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated;
    const supabase = supabaseForUser(ctx);
    let q = supabase.from("shipments").select("id,type,commodity,po_ref,invoice_number,invoice_date,date_ordered,date_received,currency,invoice_total_foreign,status,freight_provider,created_at").order("created_at", { ascending: false }).limit(limit ?? 10);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return fail(error.message);
    const rows = data ?? [];
    return ok(rows, { count: rows.length, shipments: rows });
  }
});

// src/lib/mcp/tools/prepare-erp-portal-rollout.ts
import { defineTool as defineTool21 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z20 } from "npm:zod@^4.4.3";
const prepare_erp_portal_rollout_default = defineTool21({
  name: "prepare_erp_portal_rollout",
  title: "Prepare ERP portal rollout",
  description: "Admin-only. Queries live Innovations-synced customers, excludes active portal members, and prepares invite or follow-up action cards. It never sends an email without later explicit approval.",
  inputSchema: {
    command: z20.string().trim().min(1).max(2e3).optional().describe("The admin's plain-English rollout instruction.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async ({ command }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated;
    try {
      const payload = await callPortalCopilot(ctx, {
        operation: "prepare-erp-rollout",
        command: command ?? "Roll out portal access to all ERP customers",
        inputMode: "text",
        transcriptConfirmed: false
      });
      return ok(payload, payload);
    } catch (error) {
      return fail(error instanceof Error ? error.message : "Could not prepare the ERP portal rollout");
    }
  }
});

// src/lib/mcp/tools/list-copilot-approvals.ts
import { defineTool as defineTool22 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z21 } from "npm:zod@^4.4.3";
const list_copilot_approvals_default = defineTool22({
  name: "list_copilot_approvals",
  title: "List Portal Copilot approvals",
  description: "Admin-only. Lists recent Copilot runs and the action cards for one run, including partial failures and audit-safe execution state.",
  inputSchema: {
    run_id: z21.string().uuid().optional().describe("Copilot run id. Defaults to the latest run.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ run_id }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated;
    try {
      const payload = await callPortalCopilot(ctx, { operation: "get-state", ...run_id ? { runId: run_id } : {} });
      return ok(payload, payload);
    } catch (error) {
      return fail(error instanceof Error ? error.message : "Could not load Copilot approvals");
    }
  }
});

// src/lib/mcp/tools/decide-copilot-action.ts
import { defineTool as defineTool23 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z22 } from "npm:zod@^4.4.3";
const decide_copilot_action_default = defineTool23({
  name: "decide_copilot_action",
  title: "Approve or reject a Portal Copilot action",
  description: "Admin-only. Explicitly approves or rejects one prepared action. Approval can create an internal task or create/link a portal login and queue the customer invitation email.",
  inputSchema: {
    action_id: z22.string().uuid().describe("Prepared Copilot action id."),
    decision: z22.enum(["approve", "reject"]).describe("The admin's explicit decision.")
  },
  annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: false, openWorldHint: false },
  handler: async ({ action_id, decision }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated;
    try {
      const payload = await callPortalCopilot(ctx, { operation: "decide-action", actionId: action_id, decision });
      return ok(payload, payload);
    } catch (error) {
      return fail(error instanceof Error ? error.message : "Could not apply the Copilot decision");
    }
  }
});

// src/lib/mcp/tools/admin-list-resources.ts
import { defineTool as defineTool24 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z23 } from "npm:zod@^4.4.3";

// supabase/functions/_shared/copilot/adminResources.ts
const ADMIN_RESOURCES = [
  // ---------------------------------------------------------------- CRM
  {
    key: "contacts",
    table: "contacts",
    module: "Contacts / CRM",
    description: "CRM contacts and companies, with pipeline, stage, lead score and ERP customer link.",
    select: "id,name,business_name,email,phone,pipeline,stage,lead_score,next_action_at,is_company,is_archived,linked_customer_id,notes,created_at,updated_at",
    searchColumns: ["name", "business_name", "email", "phone"],
    writable: ["name", "business_name", "email", "phone", "pipeline", "stage", "lead_score", "next_action_at", "notes", "is_archived", "linked_customer_id"],
    orderBy: "updated_at"
  },
  {
    key: "opportunities",
    table: "opportunities",
    module: "CRM",
    description: "Sales pipeline opportunities.",
    select: "*",
    searchColumns: ["name"],
    writable: ["name", "stage", "status", "expected_close_date", "contact_id", "notes", "probability"],
    orderBy: "updated_at",
    priceSensitive: true
  },
  {
    key: "activities",
    table: "activities",
    module: "CRM",
    description: "CRM activities, tasks and follow-ups.",
    select: "*",
    searchColumns: ["subject", "notes"],
    writable: ["subject", "notes", "due_at", "status", "activity_type", "contact_id", "owner_id", "channel"],
    orderBy: "created_at"
  },
  {
    key: "notes",
    table: "notes",
    module: "CRM",
    description: "Free-form notes attached to CRM records.",
    select: "*",
    searchColumns: ["content"],
    writable: ["content", "contact_id"],
    orderBy: "created_at"
  },
  {
    key: "lead_audits",
    table: "lead_audits",
    module: "Leads",
    description: "Lead audit reports produced by the lead finder.",
    select: "*",
    searchColumns: [],
    writable: [],
    orderBy: "created_at"
  },
  // ----------------------------------------------------------- Helpdesk
  {
    key: "helpdesk_tickets",
    table: "helpdesk_tickets",
    module: "Helpdesk",
    description: "Support tickets. On create, ticket number, opened time, and AI-assistant source are supplied automatically. Priority accepts Low, Normal, Medium, High, Urgent, Critical, or 0-5.",
    select: "*",
    searchColumns: ["title", "ticket_number", "description"],
    writable: ["title", "description", "stage_id", "priority", "team_id", "owner_user_id", "ticket_type_id", "partner_contact_id", "deadline", "closed_at", "source_channel"],
    orderBy: "created_at"
  },
  {
    key: "helpdesk_ticket_messages",
    table: "helpdesk_ticket_messages",
    module: "Helpdesk",
    description: "Ticket conversation entries. Internal notes are safe; customer-visible replies are a customer-facing send.",
    select: "*",
    searchColumns: ["body"],
    writable: ["ticket_id", "body", "is_internal", "author_id"],
    orderBy: "created_at"
  },
  {
    key: "helpdesk_ticket_sla_status",
    table: "helpdesk_ticket_sla_status",
    module: "Helpdesk",
    description: "SLA policy assignments and deadlines per ticket (ticket_id, sla_policy_id, deadline_at, status).",
    select: "id,ticket_id,sla_policy_id,deadline_at,reached_at,status,created_at,updated_at",
    searchColumns: [],
    writable: ["ticket_id", "sla_policy_id", "deadline_at", "reached_at", "status"],
    orderBy: "deadline_at"
  },
  {
    key: "helpdesk_sla_policies",
    table: "helpdesk_sla_policies",
    module: "Helpdesk",
    description: "SLA policy definitions (name, target hours, team).",
    select: "*",
    searchColumns: ["name"],
    writable: ["name", "target_hours", "team_id", "active"],
    orderBy: "name"
  },
  {
    key: "helpdesk_teams",
    table: "helpdesk_teams",
    module: "Helpdesk",
    description: "Helpdesk teams.",
    select: "*",
    searchColumns: ["name"],
    writable: ["name", "description", "active"],
    orderBy: "name"
  },
  {
    key: "helpdesk_ticket_stages",
    table: "helpdesk_ticket_stages",
    module: "Helpdesk",
    description: "Ticket stages / pipeline columns.",
    select: "*",
    searchColumns: ["name"],
    writable: ["name", "sequence", "is_closed", "active"],
    orderBy: "sequence"
  },
  // ------------------------------------------------------- Orders & Rx
  {
    key: "orders",
    table: "orders",
    module: "Website / Orders",
    description: "Web and portal orders.",
    select: "*",
    searchColumns: ["customer_name", "contact_email"],
    writable: ["status", "notes"],
    orderBy: "created_at",
    priceSensitive: true
  },
  {
    key: "order_items",
    table: "order_items",
    module: "Website / Orders",
    description: "Line items on a web order.",
    select: "*",
    searchColumns: ["product_name"],
    writable: ["quantity", "status"],
    orderBy: "created_at",
    priceSensitive: true
  },
  {
    key: "rx_order_submissions",
    table: "rx_order_submissions",
    module: "Website / Rx",
    description: "Rx order submissions dispatched to the lab.",
    select: "*",
    searchColumns: ["status"],
    writable: ["status", "notes"],
    orderBy: "created_at"
  },
  {
    key: "stock_order_submissions",
    table: "stock_order_submissions",
    module: "Website / Stock orders",
    description: "Stock (WSPL) order submissions.",
    select: "*",
    searchColumns: ["status"],
    writable: ["status", "notes"],
    orderBy: "created_at"
  },
  {
    key: "quotes",
    table: "quotes",
    module: "Website / Quotations",
    description: "Customer quotations.",
    select: "*",
    searchColumns: ["quote_number", "customer_name"],
    writable: ["status", "notes", "valid_until"],
    orderBy: "created_at",
    priceSensitive: true
  },
  {
    key: "quote_lines",
    table: "quote_lines",
    module: "Website / Quotations",
    description: "Quotation line items. Price-bearing.",
    select: "*",
    searchColumns: ["description"],
    writable: ["description", "quantity"],
    orderBy: "created_at",
    priceSensitive: true
  },
  // ------------------------------------------------- Catalog & pricing
  {
    key: "lenses",
    table: "lenses",
    module: "Pricing / Catalog",
    description: "Rx and stock lens catalog, including web_enabled / wspl_enabled channel flags.",
    select: "*",
    searchColumns: ["name", "description"],
    writable: ["name", "description", "is_active", "web_enabled", "wspl_enabled", "material_id", "lenstype_id", "finishtype_id", "brand_id"],
    orderBy: "updated_at",
    priceSensitive: true
  },
  {
    key: "addons",
    table: "addons",
    module: "Pricing / Catalog",
    description: "Lens add-ons and treatments.",
    select: "*",
    searchColumns: ["name", "description"],
    writable: ["name", "description", "is_active"],
    orderBy: "name",
    priceSensitive: true
  },
  {
    key: "supplies",
    table: "supplies",
    module: "Pricing / Catalog",
    description: "Optical supplies catalog.",
    select: "*",
    searchColumns: ["name", "description", "sku"],
    writable: ["name", "description", "is_active", "category_id"],
    orderBy: "name",
    priceSensitive: true
  },
  {
    key: "brands",
    table: "brands",
    module: "Pricing / Catalog",
    description: "Product brands.",
    select: "*",
    searchColumns: ["name"],
    writable: ["name", "is_active"],
    orderBy: "name"
  },
  {
    key: "price_catalog",
    table: "price_catalog",
    module: "Pricing",
    description: "Canonical website price catalog. Price-bearing.",
    select: "*",
    searchColumns: [],
    writable: ["price"],
    orderBy: "id",
    priceSensitive: true
  },
  {
    key: "price_matrix",
    table: "price_matrix",
    module: "Pricing",
    description: "Rx price matrix rows. Price-bearing.",
    select: "*",
    searchColumns: [],
    writable: ["price"],
    orderBy: "id",
    priceSensitive: true
  },
  {
    key: "pricelists",
    table: "pricelists",
    module: "Pricing",
    description: "Pricelist definitions.",
    select: "*",
    searchColumns: ["name"],
    writable: ["name"],
    orderBy: "id",
    priceSensitive: true
  },
  {
    key: "pricelist_versions",
    table: "pricelist_versions",
    module: "Pricing",
    description: "Published pricelist versions. Publishing is price-bearing.",
    select: "*",
    searchColumns: ["name"],
    writable: ["name", "status", "notes"],
    orderBy: "created_at",
    priceSensitive: true
  },
  {
    key: "catalog_templates",
    table: "catalog_templates",
    module: "Pricing / Catalog builder",
    description: "Catalog builder templates.",
    select: "*",
    searchColumns: ["name"],
    writable: ["name", "description"],
    orderBy: "updated_at"
  },
  {
    key: "store_product_overrides",
    table: "store_product_overrides",
    module: "Website / Store",
    description: "Per-product storefront overrides such as publish state.",
    select: "*",
    searchColumns: [],
    writable: ["is_published", "display_name", "sort_order"],
    orderBy: "updated_at",
    priceSensitive: true
  },
  // ------------------------------------------ Customers, portal, billing
  {
    key: "customers",
    table: "customers",
    module: "Customers",
    description: "ERP/billing customer accounts (account number, credit terms, Innovations link).",
    select: "*",
    searchColumns: ["name", "account_number", "email"],
    writable: ["name", "email", "phone", "pipeline_stage", "assigned_pricelist_id", "is_active"],
    orderBy: "updated_at"
  },
  {
    key: "profiles",
    table: "profiles",
    module: "Settings / Users",
    description: "User profiles including portal access status.",
    select: "id,email,full_name,portal_access_status,portal_access_note,crm_customer_id,created_at,updated_at",
    searchColumns: ["email", "full_name"],
    writable: ["full_name", "portal_access_status", "portal_access_note"],
    orderBy: "updated_at"
  },
  {
    key: "portal_account_memberships",
    table: "portal_account_memberships",
    module: "Customers / Portal",
    description: "Which users can act on which customer accounts.",
    select: "*",
    searchColumns: [],
    writable: ["status", "role", "customer_id", "user_id"],
    orderBy: "updated_at"
  },
  {
    key: "customer_addresses",
    table: "customer_addresses",
    module: "Customers",
    description: "Customer shipping/billing addresses.",
    select: "*",
    searchColumns: ["line1", "city", "country"],
    writable: ["label", "line1", "line2", "city", "state", "postal_code", "country", "is_default"],
    orderBy: "updated_at"
  },
  {
    key: "statements",
    table: "statements",
    module: "Customers / Billing",
    description: "Customer account statements.",
    select: "*",
    searchColumns: [],
    writable: [],
    orderBy: "created_at"
  },
  {
    key: "statement_lines",
    table: "statement_lines",
    module: "Customers / Billing",
    description: "Statement transaction lines.",
    select: "*",
    searchColumns: [],
    writable: [],
    orderBy: "created_at"
  },
  {
    key: "account_payments",
    table: "account_payments",
    module: "Customers / Billing",
    description: "Recorded account payments. Read-only here: payments are confirmed by their own governed RPC.",
    select: "*",
    searchColumns: [],
    writable: [],
    orderBy: "created_at"
  },
  {
    key: "balances",
    table: "balances",
    module: "Customers / Billing",
    description: "Customer account balances synced from the ERP.",
    select: "*",
    searchColumns: [],
    writable: [],
    orderBy: "updated_at"
  },
  // ---------------------------------------------------------- Shipments
  {
    key: "shipments",
    table: "shipments",
    module: "Costings / Shipments",
    description: "Inbound shipments and landed-cost headers.",
    select: "*",
    searchColumns: ["reference", "supplier_name"],
    writable: ["reference", "status", "notes", "arrival_date"],
    orderBy: "created_at",
    priceSensitive: true
  },
  {
    key: "shipment_lines",
    table: "shipment_lines",
    module: "Costings / Shipments",
    description: "Shipment line items.",
    select: "*",
    searchColumns: [],
    writable: ["quantity", "notes"],
    orderBy: "created_at",
    priceSensitive: true
  },
  {
    key: "shipment_charges",
    table: "shipment_charges",
    module: "Costings / Shipments",
    description: "Shipment charges used in landed-cost calculation.",
    select: "*",
    searchColumns: [],
    writable: ["charge_type_id", "amount", "notes"],
    orderBy: "created_at",
    priceSensitive: true
  },
  // ---------------------------------------- Docs, knowledge & settings
  {
    key: "docstudio_billing_documents",
    table: "docstudio_billing_documents",
    module: "Doc Studio",
    description: "Doc Studio billing documents: invoices, quotes, pro formas and receipts. Prefer the docstudio_create_document tool, which resolves the customer, the issuer details and the document number and computes the totals for you. Use this resource directly only to read documents or amend one you already created. Never invent a billing_number; never hand-write the content or totals JSON.",
    select: "*",
    searchColumns: ["document_name", "billing_number", "customer_name", "customer_company"],
    writable: [
      "document_name",
      "document_type",
      "billing_number",
      "customer_name",
      "customer_company",
      "customer_account",
      "paper_size",
      "status",
      "content",
      "totals",
      "source_document_type",
      "source_document_id"
    ],
    orderBy: "created_at"
  },
  {
    key: "docstudio_files",
    table: "docstudio_files",
    module: "Doc Studio",
    description: "Doc Studio content files. The copilot may author email and letter files; signature, social, ship-label, statement and pricelist files are edited in the studio. Content must be built with the shared content builder, not hand-written.",
    select: "id,owner_user_id,file_type,file_name,customer_name,customer_account,metadata,version,created_at,updated_at",
    searchColumns: ["file_name", "customer_name", "customer_account"],
    writable: ["file_name", "file_type", "customer_name", "customer_account", "metadata", "content"],
    orderBy: "updated_at"
  },
  {
    key: "help_articles",
    table: "help_articles",
    module: "Knowledge / Wiki",
    description: "Admin wiki and help articles.",
    select: "id,title,slug,summary,description,category,content_type,page_slug,status,updated_at",
    searchColumns: ["title", "summary", "description", "content"],
    writable: ["title", "summary", "description", "category", "content", "status", "page_slug"],
    orderBy: "updated_at"
  },
  {
    key: "blog_posts",
    table: "blog_posts",
    module: "Website / Content",
    description: "Public blog posts.",
    select: "id,title,slug,excerpt,status,published_at,updated_at",
    searchColumns: ["title", "excerpt"],
    writable: ["title", "slug", "excerpt", "content", "status", "published_at"],
    orderBy: "updated_at"
  },
  {
    key: "website_features",
    table: "website_features",
    module: "Settings",
    description: "Website feature flags.",
    select: "*",
    searchColumns: ["feature_key"],
    writable: ["enabled"],
    orderBy: "feature_key"
  },
  {
    key: "company_settings",
    table: "company_settings",
    module: "Settings",
    description: "Company profile and global settings. Also holds the issuer details every Doc Studio document is built from \u2014 letterhead address, registration numbers and bank details \u2014 so changing them here changes every document produced afterwards.",
    select: "*",
    searchColumns: [],
    // support_email / phone / address were listed here but are not columns on
    // this table; the real ones are email / tel / the split physical_* fields.
    writable: [
      "company_name",
      "email",
      "feedback_email",
      "tel",
      "fax",
      "slogan",
      "physical_line1",
      "physical_line2",
      "physical_city",
      "physical_state",
      "physical_postcode",
      "physical_country",
      "tax_tin",
      "company_reg_no",
      "base_currency",
      "default_vat",
      "bank_name",
      "bank_account_name",
      "bank_account_no",
      "bank_branch",
      "bank_swift",
      "bank_note",
      "default_paper_size",
      "default_due_days"
    ],
    orderBy: "id"
  },
  {
    key: "role_permissions",
    table: "role_permissions",
    module: "Settings / Roles",
    description: "Role to feature permission matrix. Read-only from the copilot.",
    select: "*",
    searchColumns: [],
    writable: [],
    orderBy: "id"
  }
];
const ADMIN_RESOURCE_BY_KEY = new Map(ADMIN_RESOURCES.map((resource) => [resource.key, resource]));
const findAdminResource = (key) => {
  const resource = ADMIN_RESOURCE_BY_KEY.get(key);
  if (!resource) {
    throw new Error(`Unknown resource "${key}". Call admin_list_resources to see valid keys.`);
  }
  return resource;
};
const classifyAdminWrite = (resource, operation) => {
  if (operation === "delete") {
    return { writeClass: "approval", reason: "Deletes are irreversible and need approval." };
  }
  if (resource.priceSensitive) {
    return { writeClass: "approval", reason: `${resource.key} carries price or money values, so changes need approval.` };
  }
  return { writeClass: "immediate", reason: "Reversible change \u2014 executed immediately." };
};
const sanitizeLike = (value) => `%${value.replaceAll(",", " ").replaceAll("(", " ").replaceAll(")", " ").replaceAll("%", "").replaceAll("_", "").trim()}%`;
const pickWritable = (resource, values) => {
  if (resource.writable.length === 0) {
    throw new Error(`${resource.key} is read-only.`);
  }
  const allowed = {};
  const rejected = [];
  for (const [key, value] of Object.entries(values ?? {})) {
    if (resource.writable.includes(key)) allowed[key] = value;
    else rejected.push(key);
  }
  if (Object.keys(allowed).length === 0) {
    throw new Error(`No writable fields supplied for ${resource.key}. Writable fields: ${resource.writable.join(", ")}`);
  }
  return { allowed, rejected };
};
const HELPDESK_PRIORITY_BY_LABEL = {
  low: 0,
  normal: 1,
  medium: 2,
  high: 3,
  urgent: 4,
  critical: 5
};
const normalizeHelpdeskPriority = (value) => {
  const label = typeof value === "string" ? value.trim().toLowerCase() : "";
  const numeric = label in HELPDESK_PRIORITY_BY_LABEL ? HELPDESK_PRIORITY_BY_LABEL[label] : Number(value);
  if (!Number.isInteger(numeric) || numeric < 0 || numeric > 5) {
    throw new Error("Helpdesk priority must be Low, Normal, Medium, High, Urgent, Critical, or an integer from 0 to 5.");
  }
  return numeric;
};
const newDocStudioVersion = () => {
  const bytes = new Uint8Array(8);
  crypto.getRandomValues(bytes);
  return Array.from(bytes, (b) => b.toString(16).padStart(2, "0")).join("").toUpperCase();
};
const applyDocStudioCreateDefaults = (resource, allowed, actorUserId) => {
  if (!resource.table.startsWith("docstudio_")) return;
  if (!actorUserId) {
    throw new Error("Doc Studio documents need a signed-in admin to own them; no acting user was supplied.");
  }
  allowed.owner_user_id = actorUserId;
  allowed.version = newDocStudioVersion();
  if (resource.table === "docstudio_billing_documents") {
    allowed.created_by_copilot = true;
    allowed.status = "draft";
  }
};
const normalizeAdminWriteValues = (resource, input) => {
  const values = { ...input };
  if (resource.key !== "helpdesk_tickets") return values;
  if (values.assigned_to !== void 0 && values.owner_user_id === void 0) {
    values.owner_user_id = values.assigned_to;
  }
  delete values.assigned_to;
  if (values.priority !== void 0) values.priority = normalizeHelpdeskPriority(values.priority);
  return values;
};
const clampLimit = (value, fallback = 20) => {
  const num = typeof value === "number" ? value : Number(value);
  if (!Number.isFinite(num)) return fallback;
  return Math.min(Math.max(Math.trunc(num), 1), 50);
};
const dispatchAdminResourceTool = async (db, name, input, actorUserId) => {
  if (name === "admin_list_resources") {
    const moduleFilter = typeof input.module === "string" ? input.module.toLowerCase() : "";
    const items = ADMIN_RESOURCES.filter((resource2) => !moduleFilter || resource2.module.toLowerCase().includes(moduleFilter)).map((resource2) => ({
      key: resource2.key,
      module: resource2.module,
      description: resource2.description,
      writable: resource2.writable,
      approvalOnWrite: Boolean(resource2.priceSensitive)
    }));
    return { status: "ok", resource: "*", operation: "list_resources", data: items };
  }
  const resource = findAdminResource(typeof input.resource === "string" ? input.resource : "");
  if (name === "admin_search_records") {
    const query = typeof input.query === "string" ? input.query.trim() : "";
    const limit = clampLimit(input.limit);
    let builder = db.from(resource.table).select(resource.select);
    if (query && resource.searchColumns.length > 0) {
      const like = sanitizeLike(query);
      builder = builder.or(resource.searchColumns.map((column) => `${column}.ilike.${like}`).join(","));
    }
    const filters = input.filters ?? {};
    for (const [column, value] of Object.entries(filters)) {
      builder = value === null ? builder.is(column, null) : builder.eq(column, value);
    }
    if (resource.orderBy) builder = builder.order(resource.orderBy, { ascending: false });
    const { data, error } = await builder.limit(limit);
    if (error) throw new Error(error.message);
    return { status: "ok", resource: resource.key, operation: "search", data: data ?? [] };
  }
  if (name === "admin_get_record") {
    const id = input.id;
    if (id === void 0 || id === null || id === "") throw new Error("An id is required.");
    const { data, error } = await db.from(resource.table).select(resource.select).eq("id", id).maybeSingle();
    if (error) throw new Error(error.message);
    return { status: "ok", resource: resource.key, operation: "get", data: data ?? null };
  }
  if (name === "admin_create_record" || name === "admin_update_record") {
    const operation = name === "admin_create_record" ? "create" : "update";
    const rawValues = normalizeAdminWriteValues(resource, input.values ?? {});
    const { allowed, rejected } = pickWritable(resource, rawValues);
    if (resource.key === "helpdesk_tickets" && operation === "create") {
      const title = typeof allowed.title === "string" ? allowed.title.trim() : "";
      if (!title) throw new Error("A title is required to create a Helpdesk ticket.");
      const generatedId = crypto.randomUUID();
      allowed.id = generatedId;
      allowed.ticket_number = `TCK-${generatedId.replaceAll("-", "").slice(0, 12).toUpperCase()}`;
      allowed.title = title;
      allowed.description = typeof allowed.description === "string" ? allowed.description : "";
      allowed.priority = allowed.priority ?? 1;
      allowed.source_channel = "ai_assistant";
      allowed.opened_at = (/* @__PURE__ */ new Date()).toISOString();
    }
    if (operation === "create") applyDocStudioCreateDefaults(resource, allowed, actorUserId);
    if (operation === "update" && resource.table.startsWith("docstudio_")) {
      allowed.version = newDocStudioVersion();
      allowed.updated_at = (/* @__PURE__ */ new Date()).toISOString();
    }
    const id = input.id;
    if (operation === "update" && (id === void 0 || id === null || id === "")) {
      throw new Error("An id is required to update a record.");
    }
    const { writeClass, reason } = classifyAdminWrite(resource, operation);
    if (writeClass === "approval") {
      return {
        status: "needs_approval",
        resource: resource.key,
        operation,
        reason,
        proposal: { table: resource.table, id: id ?? null, values: allowed },
        ignoredFields: rejected
      };
    }
    const builder = operation === "create" ? db.from(resource.table).insert(allowed).select(resource.select) : db.from(resource.table).update(allowed).eq("id", id).select(resource.select);
    const { data, error } = await builder;
    if (error) throw new Error(error.message);
    return { status: "ok", resource: resource.key, operation, data: data ?? [], ignoredFields: rejected };
  }
  if (name === "admin_delete_record") {
    const id = input.id;
    if (id === void 0 || id === null || id === "") throw new Error("An id is required to delete a record.");
    if (resource.writable.length === 0) throw new Error(`${resource.key} is read-only.`);
    const { reason } = classifyAdminWrite(resource, "delete");
    return {
      status: "needs_approval",
      resource: resource.key,
      operation: "delete",
      reason,
      proposal: { table: resource.table, id }
    };
  }
  throw new Error(`Unknown admin resource tool: ${name}`);
};
const RESOURCE_KEYS_HINT = ADMIN_RESOURCES.map((resource) => resource.key).join(", ");
const ADMIN_RESOURCE_TOOLS = [
  {
    name: "admin_list_resources",
    description: "List every admin data resource this copilot can read or write, with its module, writable fields, and whether writes need approval. Call this first when you are unsure which resource covers a request.",
    input_schema: {
      type: "object",
      properties: { module: { type: "string", description: 'Optional module name filter, e.g. "Helpdesk" or "Pricing".' } },
      additionalProperties: false
    }
  },
  {
    name: "admin_search_records",
    description: `Search or list records in any admin resource. Valid resource keys: ${RESOURCE_KEYS_HINT}.`,
    input_schema: {
      type: "object",
      properties: {
        resource: { type: "string", description: "Resource key." },
        query: { type: "string", description: "Optional free-text search." },
        filters: { type: "object", description: 'Optional exact-match column filters, e.g. {"status":"open"}.' },
        limit: { type: "number", description: "Max rows, 1-50 (default 20)." }
      },
      required: ["resource"],
      additionalProperties: false
    }
  },
  {
    name: "admin_get_record",
    description: "Fetch one record by id from an admin resource.",
    input_schema: {
      type: "object",
      properties: {
        resource: { type: "string" },
        id: { type: ["string", "number"] }
      },
      required: ["resource", "id"],
      additionalProperties: false
    }
  },
  {
    name: "admin_create_record",
    description: "Create a record in an admin resource. Executes immediately unless the resource is price-bearing, in which case it returns an approval proposal.",
    input_schema: {
      type: "object",
      properties: {
        resource: { type: "string" },
        values: { type: "object", description: "Column/value pairs. Only writable columns are accepted." }
      },
      required: ["resource", "values"],
      additionalProperties: false
    }
  },
  {
    name: "admin_update_record",
    description: "Update a record in an admin resource. Executes immediately unless the resource is price-bearing, in which case it returns an approval proposal.",
    input_schema: {
      type: "object",
      properties: {
        resource: { type: "string" },
        id: { type: ["string", "number"] },
        values: { type: "object" }
      },
      required: ["resource", "id", "values"],
      additionalProperties: false
    }
  },
  {
    name: "admin_delete_record",
    description: "Propose deleting a record. Deletes are irreversible and always return an approval proposal instead of executing.",
    input_schema: {
      type: "object",
      properties: {
        resource: { type: "string" },
        id: { type: ["string", "number"] }
      },
      required: ["resource", "id"],
      additionalProperties: false
    }
  }
];
const ADMIN_RESOURCE_TOOL_NAMES = new Set(ADMIN_RESOURCE_TOOLS.map((tool) => tool.name));

// src/lib/mcp/tools/admin-list-resources.ts
const admin_list_resources_default = defineTool24({
  name: "admin_list_resources",
  title: "List admin data resources",
  description: "List every admin module data resource this server can read or write (CRM, helpdesk, orders, Rx, pricing, catalog, customers, billing, shipments, docs, knowledge, settings), with writable fields and whether writes need approval. Call this first when you are unsure which resource covers a task.",
  inputSchema: {
    module: z23.string().min(1).optional().describe('Optional module filter, e.g. "Helpdesk" or "Pricing".')
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ module }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated;
    const filter = module?.toLowerCase() ?? "";
    const rows = ADMIN_RESOURCES.filter((resource) => !filter || resource.module.toLowerCase().includes(filter)).map(
      (resource) => ({
        key: resource.key,
        module: resource.module,
        description: resource.description,
        writable: resource.writable,
        approvalOnWrite: Boolean(resource.priceSensitive)
      })
    );
    return ok(rows, { count: rows.length, resources: rows });
  }
});

// src/lib/mcp/tools/admin-search-records.ts
import { defineTool as defineTool25 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z24 } from "npm:zod@^4.4.3";
const admin_search_records_default = defineTool25({
  name: "admin_search_records",
  title: "Search admin records",
  description: "Search or list records in any admin resource (see admin_list_resources for keys). Row-level security still applies, so only data the caller may see is returned.",
  inputSchema: {
    resource: z24.string().min(1).describe("Resource key from admin_list_resources."),
    query: z24.string().min(1).optional().describe("Free-text search across the resource's searchable columns."),
    filters: z24.record(z24.string(), z24.any()).optional().describe('Exact-match column filters, e.g. {"status":"open"}.'),
    limit: z24.number().int().min(1).max(50).optional().describe("Max rows (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ resource, query, filters, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated;
    try {
      const result = await dispatchAdminResourceTool(supabaseForUser(ctx), "admin_search_records", {
        resource,
        query,
        filters,
        limit
      });
      return ok(result.data, { resource, count: Array.isArray(result.data) ? result.data.length : 0, rows: result.data });
    } catch (error) {
      return fail(error instanceof Error ? error.message : "Search failed");
    }
  }
});

// src/lib/mcp/tools/admin-get-record.ts
import { defineTool as defineTool26 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z25 } from "npm:zod@^4.4.3";
const admin_get_record_default = defineTool26({
  name: "admin_get_record",
  title: "Get one admin record",
  description: "Fetch a single record by id from any admin resource (see admin_list_resources for keys).",
  inputSchema: {
    resource: z25.string().min(1).describe("Resource key from admin_list_resources."),
    id: z25.union([z25.string().min(1), z25.number()]).describe("Record id.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ resource, id }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated;
    try {
      const result = await dispatchAdminResourceTool(supabaseForUser(ctx), "admin_get_record", { resource, id });
      return ok(result.data, { resource, record: result.data });
    } catch (error) {
      return fail(error instanceof Error ? error.message : "Lookup failed");
    }
  }
});

// src/lib/mcp/tools/admin-write-record.ts
import { defineTool as defineTool27 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z26 } from "npm:zod@^4.4.3";
const admin_write_record_default = defineTool27({
  name: "admin_write_record",
  title: "Create, update or delete an admin record",
  description: "Create, update or delete a record in any admin resource. Ordinary changes execute immediately. Deletes and price-bearing changes are not executed: the tool returns an approval proposal describing exactly what would change, which an admin must approve in the Portal Copilot.",
  inputSchema: {
    resource: z26.string().min(1).describe("Resource key from admin_list_resources."),
    operation: z26.enum(["create", "update", "delete"]).describe("What to do."),
    id: z26.union([z26.string().min(1), z26.number()]).optional().describe("Record id (required for update and delete)."),
    values: z26.record(z26.string(), z26.any()).optional().describe("Column/value pairs for create and update. Only writable columns are accepted.")
  },
  annotations: { readOnlyHint: false, destructiveHint: true, openWorldHint: false },
  handler: async ({ resource, operation, id, values }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated;
    const toolName = operation === "create" ? "admin_create_record" : operation === "update" ? "admin_update_record" : "admin_delete_record";
    try {
      const result = await dispatchAdminResourceTool(supabaseForUser(ctx), toolName, { resource, id, values }, await currentUserId(ctx));
      return ok(result, {
        status: result.status,
        resource: result.resource,
        operation: result.operation,
        reason: result.reason ?? null,
        proposal: result.proposal ?? null,
        data: result.data ?? null
      });
    } catch (error) {
      return fail(error instanceof Error ? error.message : "Write failed");
    }
  }
});

// src/lib/mcp/index.ts
const projectRef = "xstmeirxhfbiyayrrsob";
const mcp_default = defineMcp({
  name: "classic-visions-mcp",
  title: "Classic Visions",
  version: "0.4.0",
  instructions: [
    "Tools for the Classic Visions optical platform (wholesale lenses, coatings and optical supplies).",
    "Every call acts as the signed-in user and row-level security decides what is visible: customers see only their own account data, staff see the wider CRM, catalog and operations data.",
    "Start with `whoami` to learn the caller's roles and linked customer accounts.",
    "Billing: `get_account_balance`, `list_statements`, `get_statement`. Orders: `list_orders`, `get_order`. Quotes: `list_quotes`, `get_quote`.",
    "Support: `list_support_tickets`, `get_support_ticket`, `create_support_ticket`, `reply_to_support_ticket`.",
    "Catalog and knowledge: `search_products`, `list_pricelists`, `search_knowledge_base`.",
    "Staff operations: `search_crm`, `list_crm_tasks`, `create_crm_task`, `list_opportunities`, `list_shipments`.",
    "Admin-wide data access: `admin_list_resources`, `admin_search_records`, `admin_get_record`, `admin_write_record` reach every admin module (CRM, helpdesk, orders, Rx, pricing, catalog, customers, billing, shipments, docs, knowledge, settings). Ordinary writes execute immediately; deletes and price-bearing writes return an approval proposal instead.",
    "Admin Portal Copilot: `prepare_erp_portal_rollout`, `list_copilot_approvals`, `decide_copilot_action`. Customer-facing effects always require an explicit approve decision.",
    "Never quote or invent prices that did not come from these tools, and never promise discounts, credit terms or delivery dates."
  ].join(" "),
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    whoami_default,
    search_products_default,
    list_my_orders_default,
    get_order_default,
    list_statements_default,
    get_statement_default,
    get_account_balance_default,
    list_quotes_default,
    get_quote_default,
    list_support_tickets_default,
    get_support_ticket_default,
    create_support_ticket_default,
    reply_to_support_ticket_default,
    search_knowledge_base_default,
    search_crm_default,
    list_crm_tasks_default,
    create_crm_task_default,
    list_opportunities_default,
    list_pricelists_default,
    list_shipments_default,
    prepare_erp_portal_rollout_default,
    list_copilot_approvals_default,
    decide_copilot_action_default,
    admin_list_resources_default,
    admin_search_records_default,
    admin_get_record_default,
    admin_write_record_default
  ]
});

// classic-visions-mcp-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
