import { useEffect, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Bot, Loader2, Lock, ShieldCheck } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { useToast } from "@/hooks/use-toast";

type Settings = { project_id: string | null; location: "us" | "eu"; processor_id: string | null; enabled: boolean; has_service_account: boolean; status: string; last_error: string | null };

export default function DocumentAiIntegrationCard() {
  const qc = useQueryClient(); const { toast } = useToast();
  const { data } = useQuery({ queryKey: ["document-ai-settings"], queryFn: async () => { const { data, error } = await (supabase.from("document_ai_settings") as any).select("project_id,location,processor_id,enabled,has_service_account,status,last_error").eq("tenant_key", "default").maybeSingle(); if (error) throw error; return data as Settings | null; } });
  const [form, setForm] = useState({ projectId: "classic-visions", location: "us", processorId: "", enabled: false, serviceAccountJson: "" });
  useEffect(() => { if (data) setForm((current) => ({ ...current, projectId: data.project_id ?? "", location: data.location, processorId: data.processor_id ?? "", enabled: data.enabled })); }, [data]);
  const save = useMutation({ mutationFn: async () => { const { error } = await supabase.rpc("upsert_document_ai_settings" as never, { p_project_id: form.projectId, p_location: form.location, p_processor_id: form.processorId, p_enabled: form.enabled, p_service_account_json: form.serviceAccountJson || null } as never); if (error) throw error; }, onSuccess: () => { setForm((current) => ({ ...current, serviceAccountJson: "" })); qc.invalidateQueries({ queryKey: ["document-ai-settings"] }); toast({ title: "Document AI saved", description: "The service-account credential remains encrypted and is never shown again." }); }, onError: (error: any) => toast({ title: "Unable to save Document AI", description: error.message, variant: "destructive" }) });
  const test = useMutation({ mutationFn: async () => { const { data, error } = await supabase.functions.invoke("document-ai", { body: { operation: "test" } }); if (error || !data?.ok) throw error ?? new Error(data?.error ?? "Test failed."); }, onSuccess: () => { qc.invalidateQueries({ queryKey: ["document-ai-settings"] }); toast({ title: "Document AI connected", description: "The stored service identity can request an access token." }); }, onError: (error: any) => toast({ title: "Document AI test failed", description: error.message, variant: "destructive" }) });
  return <Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><Bot className="h-4 w-4" /> Google Document AI</CardTitle><CardDescription>OCR is used only to create evidence-backed shipment-document drafts. Iris must ask for approval before creating costing data or learning a document layout.</CardDescription></CardHeader><CardContent className="space-y-3"><div className="grid gap-3 md:grid-cols-3"><div><Label>Google Cloud project</Label><Input value={form.projectId} onChange={(e) => setForm((p) => ({ ...p, projectId: e.target.value }))} /></div><div><Label>Region</Label><Input value={form.location} onChange={(e) => setForm((p) => ({ ...p, location: e.target.value }))} placeholder="us" /></div><div><Label>OCR processor ID</Label><Input value={form.processorId} onChange={(e) => setForm((p) => ({ ...p, processorId: e.target.value }))} /></div></div><div><Label className="flex items-center gap-2"><Lock className="h-4 w-4" /> Service-account JSON</Label><Input type="password" value={form.serviceAccountJson} onChange={(e) => setForm((p) => ({ ...p, serviceAccountJson: e.target.value }))} placeholder={data?.has_service_account ? "Leave empty to keep the encrypted credential" : "Paste the Google service-account JSON"} autoComplete="off" />{data?.has_service_account && <p className="mt-1 flex items-center gap-1 text-xs text-muted-foreground"><ShieldCheck className="h-3 w-3 text-emerald-600" /> A credential is stored.</p>}</div><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.enabled} onChange={(e) => setForm((p) => ({ ...p, enabled: e.target.checked }))} /> Enable OCR drafting</label>{data?.last_error && <p className="text-xs text-destructive">Last test: {data.last_error}</p>}<div className="flex gap-2"><Button onClick={() => save.mutate()} disabled={save.isPending}>{save.isPending && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}Save</Button><Button variant="outline" onClick={() => test.mutate()} disabled={test.isPending || !data?.has_service_account || !data?.enabled}>{test.isPending && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}Test configuration</Button></div></CardContent></Card>;
}
