import {
  DollarSign, ShoppingCart, Users, Target, LifeBuoy, Globe, BookOpen, Settings,
} from 'lucide-react';

export type AppKey = keyof typeof ADMIN_APPS;

export const ADMIN_APPS = {
  pricing: {
    key: 'pricing' as const,
    title: 'Pricing',
    icon: DollarSign,
    baseRoute: '/admin/pricing',
    defaultRoute: '/admin/pricing/catalog',
    featurePrefix: 'pricing',
    sidebarItems: [
      { label: 'Product Catalog', route: '/admin/pricing/catalog' },
      { label: 'RX Lens Prices', route: '/admin/pricing/rx-lenses' },
      { label: 'Stock Lens Prices', route: '/admin/pricing/stock-lenses' },
      { label: 'Supplies Prices', route: '/admin/pricing/supplies' },
      { label: 'Catalog Publisher', route: '/admin/pricing/publisher' },
      { label: 'Import Costings', route: '/admin/pricing/costings' },
      { label: 'Costing Reports', route: '/admin/pricing/costings/reports' },
      { label: 'Reference Data', route: '/admin/pricing/reference' },
      { label: 'Imports', route: '/admin/pricing/imports' },
    ],
  },
  sales: {
    key: 'sales' as const,
    title: 'Sales',
    icon: ShoppingCart,
    baseRoute: '/admin/sales',
    defaultRoute: '/admin/sales/quotations',
    featurePrefix: 'sales',
    sidebarItems: [
      { label: 'Quotations', route: '/admin/sales/quotations' },
      { label: 'Web Orders', route: '/admin/sales/web-orders' },
      { label: 'RX Orders', route: '/admin/sales/rx-orders' },
    ],
  },
  contacts: {
    key: 'contacts' as const,
    title: 'Contacts',
    icon: Users,
    baseRoute: '/admin/contacts',
    defaultRoute: '/admin/contacts',
    featurePrefix: 'contacts',
    sidebarItems: [
      { label: 'All Contacts', route: '/admin/contacts' },
      { label: 'Tags Config', route: '/admin/contacts/config/tags' },
      { label: 'Industries Config', route: '/admin/contacts/config/industries' },
    ],
  },
  leads: {
    key: 'leads' as const,
    title: 'Leads',
    icon: Target,
    baseRoute: '/admin/leads',
    defaultRoute: '/admin/leads/finder',
    featurePrefix: 'leads',
    sidebarItems: [
      { label: 'Lead Finder', route: '/admin/leads/finder' },
      { label: 'My Leads', route: '/admin/leads' },
      { label: 'Campaigns & Sequences', route: '/admin/leads/campaigns' },
      { label: 'Audit Reports', route: '/admin/leads/reports' },
      { label: 'AI Assistant', route: '/admin/leads/ai' },
      { label: 'Settings', route: '/admin/leads/settings' },
    ],
  },
  crm: {
    key: 'crm' as const,
    title: 'CRM',
    icon: Target,
    baseRoute: '/admin/crm',
    defaultRoute: '/admin/crm/pipeline',
    featurePrefix: 'crm',
    sidebarItems: [
      { label: 'Pipeline', route: '/admin/crm/pipeline' },
      { label: 'Activities', route: '/admin/crm/activities' },
    ],
  },
  helpdesk: {
    key: 'helpdesk' as const,
    title: 'Helpdesk',
    icon: LifeBuoy,
    baseRoute: '/admin/helpdesk',
    defaultRoute: '/admin/helpdesk/tickets',
    featurePrefix: 'helpdesk',
    sidebarItems: [
      { label: 'Tickets', route: '/admin/helpdesk/tickets' },
      { label: 'Teams', route: '/admin/helpdesk/teams' },
      { label: 'SLA Policies', route: '/admin/helpdesk/sla' },
    ],
  },
  website: {
    key: 'website' as const,
    title: 'Website',
    icon: Globe,
    baseRoute: '/admin/website',
    defaultRoute: '/admin/website/content',
    featurePrefix: 'website',
    sidebarItems: [
      { label: 'Pages / Content', route: '/admin/website/content' },
      { label: 'Brand Microsites', route: '/admin/website/microsites' },
      { label: 'Patient Portals', route: '/admin/website/portals' },
      { label: 'Store / Products', route: '/admin/website/store' },
    ],
  },
  knowledge: {
    key: 'knowledge' as const,
    title: 'Knowledge',
    icon: BookOpen,
    baseRoute: '/admin/knowledge',
    defaultRoute: '/admin/knowledge/wiki',
    featurePrefix: 'knowledge',
    sidebarItems: [
      { label: 'Wiki', route: '/admin/knowledge/wiki' },
      { label: 'Help Articles', route: '/admin/knowledge/help' },
    ],
  },
  settings: {
    key: 'settings' as const,
    title: 'Settings',
    icon: Settings,
    baseRoute: '/admin/settings',
    defaultRoute: '/admin/settings/company',
    featurePrefix: 'settings',
    sidebarItems: [
      { label: 'Company', route: '/admin/settings/company' },
      { label: 'Users', route: '/admin/settings/users' },
      { label: 'Roles & Permissions', route: '/admin/settings/roles' },
      { label: 'Audit Log', route: '/admin/settings/audit' },
      { label: 'Integrations', route: '/admin/settings/integrations' },
    ],
  },
} as const;
