#!/usr/bin/env node
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { build } from "esbuild";

const repoRoot = process.cwd();
const outputPath = path.join(repoRoot, "supabase", "functions", "mcp", "index.ts");
const projectRef = process.env.SUPABASE_PROJECT_REF?.trim();

if (!projectRef) {
  console.error("SUPABASE_PROJECT_REF is required to generate the MCP function.");
  process.exit(1);
}

const packageJson = JSON.parse(readFileSync(path.join(repoRoot, "package.json"), "utf8"));
const dependencyVersions = {
  ...packageJson.peerDependencies,
  ...packageJson.devDependencies,
  ...packageJson.dependencies,
};
const mcpVersion = JSON.parse(
  readFileSync(path.join(repoRoot, "node_modules", "@lovable.dev", "mcp-js", "package.json"), "utf8"),
).version;

function npmSpecifier(specifier) {
  const packageName = specifier.startsWith("@")
    ? specifier.split("/").slice(0, 2).join("/")
    : specifier.split("/")[0];
  const subpath = specifier.slice(packageName.length);
  const version = packageName === "@lovable.dev/mcp-js" ? mcpVersion : dependencyVersions[packageName];
  return version ? `npm:${packageName}@${version}${subpath}` : `npm:${specifier}`;
}

const result = await build({
  stdin: {
    contents: [
      'import mcp from "./src/lib/mcp/index.ts";',
      'import { createSupabaseHandler } from "@lovable.dev/mcp-js/stacks/supabase";',
      'Deno.serve(createSupabaseHandler(mcp, { functionName: "mcp" }));',
    ].join("\n"),
    resolveDir: repoRoot,
    sourcefile: "classic-visions-mcp-entry.ts",
    loader: "ts",
  },
  absWorkingDir: repoRoot,
  bundle: true,
  write: false,
  format: "esm",
  platform: "neutral",
  target: "esnext",
  logLevel: "silent",
  define: {
    "import.meta.env": JSON.stringify({ VITE_SUPABASE_PROJECT_ID: projectRef }),
    "import.meta.env.VITE_SUPABASE_PROJECT_ID": JSON.stringify(projectRef),
  },
  plugins: [{
    name: "externalize-bare-dependencies-for-deno",
    setup(pluginBuild) {
      pluginBuild.onResolve({ filter: /.*/ }, (args) => {
        const specifier = args.path;
        if (specifier.startsWith(".") || specifier.startsWith("/") || /^(npm|node|jsr|https?|data):/.test(specifier)) return null;
        return { path: npmSpecifier(specifier), external: true };
      });
    },
  }],
});

const bundled = result.outputFiles[0]?.text ?? "";
const generated = [
  "// AUTO-GENERATED by scripts/generate_mcp_function.mjs — do not edit.",
  "// Regenerate only with npm run mcp:generate before deploying the MCP function.",
  "// supabase function: mcp",
  "// Bundled from src/lib/mcp/index.ts.",
  bundled,
].join("\n");

if (!generated.includes("createSupabaseHandler") || generated.includes("npm:C:\\")) {
  console.error("MCP generation produced a non-portable Edge Function artifact.");
  process.exit(1);
}

mkdirSync(path.dirname(outputPath), { recursive: true });
writeFileSync(outputPath, generated, "utf8");

console.log(`Generated portable MCP Edge Function for ${projectRef}.`);
