import { createRequire } from 'node:module';
import { readFileSync } from 'node:fs';
import assert from 'node:assert/strict';
const require = createRequire(process.env.ATLAS_SQL_TEST_MODULE_PATH || import.meta.url);
const { PGlite } = require('@electric-sql/pglite');
const db = new PGlite();
const admin = '00000000-0000-4000-8000-000000000001';
const viewer = '00000000-0000-4000-8000-000000000002';
const other = '00000000-0000-4000-8000-000000000003';
const anonymous = '00000000-0000-4000-8000-000000000004';
const page = '00000000-0000-4000-8000-000000000011';
await db.exec(`
  CREATE ROLE anon; CREATE ROLE authenticated;
  CREATE SCHEMA auth;
  CREATE TABLE auth.users(id uuid PRIMARY KEY, email text, is_anonymous boolean DEFAULT false);
  CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql AS $$ SELECT nullif(current_setting('request.jwt.claim.sub', true), '')::uuid $$;
  CREATE FUNCTION public.has_role(actor uuid, wanted text) RETURNS boolean LANGUAGE sql AS $$ SELECT actor = '${admin}'::uuid AND wanted = 'admin' $$;
  GRANT USAGE ON SCHEMA auth TO authenticated, anon;
  GRANT EXECUTE ON FUNCTION auth.uid() TO authenticated, anon;
  CREATE TABLE public.help_articles(id uuid PRIMARY KEY, title text, status text, is_active boolean, body_json jsonb, content text, version_number integer, published_at timestamptz, draft_title text, draft_body_json jsonb);
  ALTER TABLE public.help_articles ENABLE ROW LEVEL SECURITY;
  GRANT SELECT ON public.help_articles TO authenticated;
  CREATE POLICY staff_only ON public.help_articles FOR SELECT TO authenticated USING (public.has_role(auth.uid(), 'admin'));
  INSERT INTO auth.users(id,email,is_anonymous) VALUES ('${admin}','admin@example.test',false),('${viewer}','viewer@example.test',false),('${other}','other@example.test',false),('${anonymous}',null,true);
  INSERT INTO public.help_articles VALUES ('${page}','Live title','published',true,'{"blocks":[{"type":"paragraph","children":[{"type":"text","text":"Live body"}]}]}','live',3,now(),'Private draft','{"blocks":[]}');
`);
await db.exec(readFileSync(new URL('../supabase/migrations/20261008183727_atlas_shared_pages.sql', import.meta.url), 'utf8'));
const actor = async (id, role = 'authenticated') => {
  await db.exec('RESET ROLE');
  await db.query(`SELECT set_config('request.jwt.claim.sub', $1, false)`, [id]);
  await db.exec(`SET ROLE ${role}`);
};
const open = async (token) => (await db.query('SELECT public.atlas_open_shared_page($1) AS page', [token])).rows[0].page;
let checks = 0;
const check = (actual, expected) => { assert.deepEqual(actual, expected); checks++; };
await actor(admin);
const share = (await db.query('SELECT public.atlas_set_page_sharing($1, true) AS share', [page])).rows[0].share;
check(share.enabled, true);
await actor(viewer);
check((await db.query('SELECT * FROM public.help_articles')).rows, []);
check((await db.query('SELECT * FROM public.atlas_page_shares')).rows, []);
check((await db.query('SELECT * FROM public.atlas_page_accesses')).rows, []);
const content = await open(share.token);
check(Object.keys(content).sort(), ['title','body','legacyContent','version','publishedAt','fullWidth'].sort());
check(content.title, 'Live title'); check(content.fullWidth, false);
check(content.body.blocks[0].children[0].text, 'Live body');
await assert.rejects(db.query('SELECT public.atlas_set_page_sharing($1, false)', [page]), /Administrator/); checks++;
await assert.rejects(db.query(`INSERT INTO public.atlas_page_accesses(page_id,page_title,version_number) VALUES ($1,'fake',1)`, [page]), /permission denied/); checks++;
await actor(other);
check((await open(share.token)).title, 'Live title'); // forwarded link accepted, no recipient assignment
await actor('', 'anon');
await assert.rejects(open(share.token), /permission denied/); checks++;
await actor('');
await assert.rejects(open(share.token), /Sign in required/); checks++;
await actor(anonymous);
await assert.rejects(open(share.token), /Sign in required/); checks++;
await actor(admin);
const logs = (await db.query('SELECT user_id, account_email, version_number FROM public.atlas_page_accesses ORDER BY account_email')).rows;
check(logs.length, 2); check(logs.map(r => r.user_id).sort(), [viewer, other].sort());
check(logs.every(r => r.version_number === 3), true);
await db.exec('RESET ROLE');
await db.query('UPDATE public.help_articles SET title=$1, full_width=true WHERE id=$2', ['Renamed title', page]);
await actor(viewer);
const renamed = await open(share.token); check(renamed.title, 'Renamed title'); check(renamed.fullWidth, true);
await actor(admin);
const disabled = (await db.query('SELECT public.atlas_set_page_sharing($1, false) AS share', [page])).rows[0].share;
check(disabled.token, share.token);
await actor(viewer); check(await open(share.token), null);
await actor(admin); await db.query('SELECT public.atlas_set_page_sharing($1, true)', [page]);
for (const patch of ["status='draft'", "status='archived'", "status=NULL", "is_active=false", "is_active=NULL", `body_json='{"lock":{},"blocks":[]}'::jsonb`, `body_json='{"blocks":[{"type":"paragraph","children":[{"type":"secret","value":"hidden"}]}]}'::jsonb`]) {
  await db.exec('RESET ROLE');
  await db.query(`UPDATE public.help_articles SET status='published', is_active=true, body_json='{"blocks":[]}'::jsonb WHERE id=$1`, [page]);
  await db.query(`UPDATE public.help_articles SET ${patch} WHERE id=$1`, [page]);
  await actor(viewer); check(await open(share.token), null);
  await actor(admin); await assert.rejects(db.query('SELECT public.atlas_set_page_sharing($1, true)', [page]), /Only active published/); checks++;
}
await actor(viewer);
check(await open('00000000-0000-4000-8000-000000000099'), null);
await actor(admin); check((await db.query('SELECT count(*)::int AS n FROM public.atlas_page_accesses')).rows[0].n, 3);
await db.exec('RESET ROLE');
await db.query(`UPDATE public.help_articles SET status='published', is_active=true, body_json='{"blocks":[]}'::jsonb WHERE id=$1`, [page]);
await db.exec(`CREATE FUNCTION public.reject_fixture_audit() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'fixture audit failure'; END $$; CREATE TRIGGER fixture_audit_failure BEFORE INSERT ON public.atlas_page_accesses FOR EACH ROW EXECUTE FUNCTION public.reject_fixture_audit();`);
await actor(viewer); await assert.rejects(open(share.token), /fixture audit failure/); checks++;
await actor(admin); check((await db.query('SELECT count(*)::int AS n FROM public.atlas_page_accesses')).rows[0].n, 3);
await db.exec('RESET ROLE');
await db.query('DELETE FROM public.help_articles WHERE id=$1', [page]);
await actor(viewer); check(await open(share.token), null);
await actor(admin); check((await db.query('SELECT count(*)::int AS n FROM public.atlas_page_accesses')).rows[0].n, 3);
await db.close();
console.log(`Atlas sharing SQL: ${checks} checks passed (isolated PostgreSQL WASM; no hosted writes).`);
