import { addDays, format } from "date-fns";
import type { AgendaSection, BusinessPlan, Issue, Meeting, Metric, MoonshotSettings, MoonshotUser, OneOnOneTemplate, OrgChart, Rock, Seat, SeatFitReview, Todo } from "./types";

const today = new Date();
const now = format(today, "yyyy-MM-dd'T'HH:mm:ss");

const cvAgenda: AgendaSection[] = [
  { id: "a1", title: "Check-in", minutes: 5 },
  { id: "a2", title: "Rocks", minutes: 5 },
  { id: "a3", title: "Scorecard", minutes: 5 },
  { id: "a4", title: "Good News", minutes: 5 },
  { id: "a5", title: "Actions", minutes: 7 },
  { id: "a6", title: "Rapid Fire / IDS", minutes: 180 },
  { id: "a7", title: "Conclude & Accountability", minutes: 8 },
];

// Build metric points from real Bloom Growth CSV export data
const pts = (pairs: [string, number][]) =>
  pairs.map(([date, value]) => ({ date, value }));

// ─── USERS ───────────────────────────────────────────────────────────────────
export const seedUsers: MoonshotUser[] = [
  {
    id: "u1",
    name: "Russell Hunte",
    email: "russell@classicvisions.net",
    role: "Owner / Visionary",
    avatar: "RH",
    seatsUsed: 1,
    seatIds: ["s1"],
    status: "active",
    invitation: { status: "accepted", pendingAt: now, acceptedAt: now },
  },
  {
    id: "u2",
    name: "Elizabeth Ward",
    email: "liz@classicvisions.net",
    role: "Finance & Administration",
    avatar: "EW",
    seatsUsed: 1,
    seatIds: ["s2"],
    supervisorId: "u1",
    status: "active",
    invitation: { status: "accepted", pendingAt: now, acceptedAt: now },
  },
  {
    id: "u3",
    name: "Roy Hunte",
    email: "roy.hunte@classicvisions.net",
    role: "Operations Manager",
    avatar: "RO",
    seatsUsed: 1,
    seatIds: ["s3"],
    supervisorId: "u1",
    status: "active",
    invitation: { status: "accepted", pendingAt: now, acceptedAt: now },
  },
  {
    id: "u4",
    name: "Randall Hunte",
    email: "info@classicvisions.net",
    role: "IT & Systems",
    avatar: "RA",
    seatsUsed: 1,
    seatIds: ["s4"],
    supervisorId: "u1",
    status: "active",
    invitation: { status: "accepted", pendingAt: now, acceptedAt: now },
  },
  {
    id: "u5",
    name: "Charlene Krassoi",
    email: "charlene@ubt.com",
    role: "Business Coach",
    avatar: "CK",
    seatsUsed: 1,
    seatIds: ["s5"],
    supervisorId: "u1",
    status: "active",
    invitation: { status: "accepted", pendingAt: now, acceptedAt: now },
  },
];

// ─── SEATS ───────────────────────────────────────────────────────────────────
export const seedSeats: Seat[] = [
  {
    id: "s1",
    name: "Owner / Visionary",
    department: "Leadership",
    capacity: 1,
    seatType: "leadership",
    roleExpectations: "Sets company direction, owns quarterly priorities, drives customer development and growth strategy.",
    competencyRubric: "Vision (5), Decision quality (5), Accountability (4), Coaching (4)",
  },
  {
    id: "s2",
    name: "Finance & Administration",
    department: "Finance",
    reportsToSeatId: "s1",
    capacity: 1,
    seatType: "individual",
    roleExpectations: "Owns GP margin tracking, monthly close, payroll, and financial reporting accuracy.",
    competencyRubric: "Accuracy (5), Analysis (4), Timeliness (4), Communication (4)",
  },
  {
    id: "s3",
    name: "Operations Manager",
    department: "Operations",
    reportsToSeatId: "s1",
    capacity: 1,
    seatType: "management",
    roleExpectations: "Runs daily production, manages WIP, reduces breakages, and ensures orders ship on time.",
    competencyRubric: "Execution (5), Quality control (4), Process improvement (4), Team management (4)",
  },
  {
    id: "s4",
    name: "IT & Systems",
    department: "Operations",
    reportsToSeatId: "s1",
    capacity: 1,
    seatType: "individual",
    roleExpectations: "Maintains business systems, drives automation, and supports cross-training across roles.",
    competencyRubric: "Technical depth (5), Reliability (4), Documentation (4), Proactivity (4)",
  },
  {
    id: "s5",
    name: "Business Coach",
    department: "Leadership",
    reportsToSeatId: "s1",
    capacity: 1,
    seatType: "individual",
    roleExpectations: "Facilitates quarterly planning, holds leadership accountable to the business plan, and coaches team development.",
    competencyRubric: "Facilitation (5), Strategic thinking (5), Coaching (5), Follow-through (4)",
  },
];

// ─── ORG CHART ───────────────────────────────────────────────────────────────
export const seedOrgChart: OrgChart = {
  seats: [
    { id: "org1", title: "Owner / Visionary", department: "Leadership", vacancyStatus: "filled", parentId: null, childIds: ["org2", "org3", "org4", "org5"], assignedUserIds: ["u1"] },
    { id: "org2", title: "Finance & Administration", department: "Finance", vacancyStatus: "filled", parentId: "org1", childIds: [], assignedUserIds: ["u2"] },
    { id: "org3", title: "Operations Manager", department: "Operations", vacancyStatus: "filled", parentId: "org1", childIds: [], assignedUserIds: ["u3"] },
    { id: "org4", title: "IT & Systems", department: "Operations", vacancyStatus: "filled", parentId: "org1", childIds: [], assignedUserIds: ["u4"] },
    { id: "org5", title: "Business Coach", department: "Leadership", vacancyStatus: "filled", parentId: "org1", childIds: [], assignedUserIds: ["u5"] },
  ],
};

// ─── 1:1s ────────────────────────────────────────────────────────────────────
export const seedOneOnOnes: OneOnOneTemplate[] = [
  {
    id: "o11_1",
    title: "Leadership 1:1 – Russell & Roy",
    cadence: "weekly",
    participantIds: ["u1", "u3"],
    agendaNotes: "Review production scorecard, breakages, WIP levels, and upcoming priorities.",
    actionItems: [
      { id: "o11a_1", text: "Update WIP tracking sheet", ownerId: "u3", dueDate: format(addDays(today, 3), "yyyy-MM-dd"), completed: false },
      { id: "o11a_2", text: "Review Q2 lens procurement plan", ownerId: "u1", dueDate: format(addDays(today, 7), "yyyy-MM-dd"), completed: false },
    ],
    createdBy: "u1",
    createdAt: format(addDays(today, -30), "yyyy-MM-dd"),
    updatedAt: format(addDays(today, -1), "yyyy-MM-dd"),
  },
  {
    id: "o11_2",
    title: "Leadership 1:1 – Russell & Elizabeth",
    cadence: "weekly",
    participantIds: ["u1", "u2"],
    agendaNotes: "Finance review: GP margin, outstanding payments, payroll status.",
    actionItems: [
      { id: "o11a_3", text: "Pull monthly GP report", ownerId: "u2", dueDate: format(addDays(today, 5), "yyyy-MM-dd"), completed: false },
      { id: "o11a_4", text: "Discuss drivers to increase GP", ownerId: "u1", dueDate: format(addDays(today, 5), "yyyy-MM-dd"), completed: false },
    ],
    createdBy: "u1",
    createdAt: format(addDays(today, -30), "yyyy-MM-dd"),
    updatedAt: format(addDays(today, -2), "yyyy-MM-dd"),
  },
];

// ─── SEAT FIT REVIEWS ────────────────────────────────────────────────────────
export const seedSeatFitReviews: SeatFitReview[] = [
  {
    id: "sfr_1",
    userId: "u1",
    seatId: "s1",
    valuesMatch: 5,
    roleCompetency: 5,
    performanceConfidence: 5,
    fitStatus: "Great fit",
    reviewCadence: "quarterly",
    roleExpectations: "Visionary leader driving strategy, customer development, and long-term growth.",
    competencyRubric: "Vision 5/5, Decision quality 5/5, Accountability 5/5",
    notes: "Strong strategic thinking and customer focus. Continue driving growth initiatives.",
    reviewDate: format(addDays(today, 30), "yyyy-MM-dd"),
    updatedAt: format(today, "yyyy-MM-dd"),
  },
  {
    id: "sfr_2",
    userId: "u3",
    seatId: "s3",
    valuesMatch: 5,
    roleCompetency: 4,
    performanceConfidence: 4,
    fitStatus: "Great fit",
    reviewCadence: "quarterly",
    roleExpectations: "Run daily production, manage WIP, reduce breakages, ensure on-time shipping.",
    competencyRubric: "Execution 5/5, Quality control 4/5, Process improvement 4/5",
    notes: "Strong operational knowledge. Continue building process documentation and QC discipline.",
    reviewDate: format(addDays(today, 45), "yyyy-MM-dd"),
    updatedAt: format(today, "yyyy-MM-dd"),
  },
  {
    id: "sfr_3",
    userId: "u2",
    seatId: "s2",
    valuesMatch: 4,
    roleCompetency: 4,
    performanceConfidence: 4,
    fitStatus: "Good fit",
    reviewCadence: "quarterly",
    roleExpectations: "Own GP tracking, monthly close, payroll, and financial reporting accuracy.",
    competencyRubric: "Accuracy 5/5, Analysis 4/5, Timeliness 4/5",
    notes: "Detail-oriented and reliable. Focus on timely GP reporting and actionable insights.",
    reviewDate: format(addDays(today, 45), "yyyy-MM-dd"),
    updatedAt: format(today, "yyyy-MM-dd"),
  },
];

// ─── MEETINGS ────────────────────────────────────────────────────────────────
export const seedMeetings: Meeting[] = [
  {
    id: "m1",
    title: "Classic Visions Leadership Weekly Meeting",
    owner: "Russell Hunte",
    date: format(addDays(today, 1), "yyyy-MM-dd"),
    status: "Scheduled",
    notes: "Weekly scorecard review + IDS on top issues",
    frequency: "weekly",
    duration: 215,
    attendeeIds: ["u1", "u2", "u3", "u4", "u5"],
    agenda: cvAgenda,
    checkInPrompt: "What's one thing you're grateful for today?",
    checkInResponse: "",
    summary: "",
  },
  {
    id: "m2",
    title: "Business Insight – Management Meeting",
    owner: "Russell Hunte",
    date: format(addDays(today, 3), "yyyy-MM-dd"),
    status: "Scheduled",
    notes: "Strategic review and business development updates",
    frequency: "monthly",
    duration: 90,
    attendeeIds: ["u1", "u2"],
    agenda: cvAgenda,
    checkInPrompt: "What's your biggest win this month?",
    checkInResponse: "",
    summary: "",
  },
  {
    id: "m3",
    title: "Business Insight – Operations / HR Meeting",
    owner: "Roy Hunte",
    date: format(addDays(today, 5), "yyyy-MM-dd"),
    status: "Scheduled",
    notes: "Production, staffing, and process improvements",
    frequency: "monthly",
    duration: 60,
    attendeeIds: ["u1", "u3", "u4"],
    agenda: cvAgenda,
    checkInPrompt: "What process improvement are you most proud of this week?",
    checkInResponse: "",
    summary: "",
  },
  {
    id: "m4",
    title: "Classic All Team Meeting",
    owner: "Russell Hunte",
    date: format(addDays(today, 7), "yyyy-MM-dd"),
    status: "Scheduled",
    notes: "Company-wide updates, core values recognition, Q&A",
    frequency: "monthly",
    duration: 60,
    attendeeIds: ["u1", "u2", "u3", "u4"],
    agenda: cvAgenda,
    checkInPrompt: "Share a recent win or good news from your area.",
    checkInResponse: "",
    summary: "",
  },
];

// ─── METRICS / SCORECARD (real data from Bloom Growth CSV export) ─────────────
export const seedMetrics: Metric[] = [
  {
    id: "k1",
    name: "Weekly Orders Received",
    owner: "Roy Hunte",
    target: 150,
    actual: 152,
    trend: "down",
    week: "W1",
    frequency: "weekly",
    unit: "number",
    points: pts([
      ["Mar 9", 173], ["Mar 16", 183], ["Mar 23", 128], ["Mar 30", 135],
      ["Apr 6", 157], ["Apr 13", 139], ["Apr 20", 162], ["Apr 27", 179],
      ["May 4", 100], ["May 11", 177], ["May 18", 160], ["May 25", 151],
      ["Jun 1", 186], ["Jun 8", 152],
    ]),
  },
  {
    id: "k2",
    name: "Weekly Orders Shipped",
    owner: "Roy Hunte",
    target: 150,
    actual: 136,
    trend: "down",
    week: "W1",
    frequency: "weekly",
    unit: "number",
    points: pts([
      ["Mar 9", 147], ["Mar 16", 183], ["Mar 23", 202], ["Mar 30", 153],
      ["Apr 6", 153], ["Apr 13", 141], ["Apr 20", 134], ["Apr 27", 171],
      ["May 4", 138], ["May 11", 147], ["May 18", 172], ["May 25", 175],
      ["Jun 1", 181], ["Jun 8", 136],
    ]),
  },
  {
    id: "k3",
    name: "Amount of Work In Progress",
    owner: "Roy Hunte",
    target: 140,
    actual: 124,
    trend: "up",
    week: "W1",
    frequency: "weekly",
    unit: "number",
    points: pts([
      ["Mar 9", 156], ["Mar 16", 165], ["Mar 23", 199], ["Mar 30", 189],
      ["Apr 6", 114], ["Apr 13", 117], ["Apr 20", 114], ["Apr 27", 142],
      ["May 4", 150], ["May 11", 111], ["May 18", 137], ["May 25", 125],
      ["Jun 1", 102], ["Jun 8", 124],
    ]),
  },
  {
    id: "k4",
    name: "Breakages Per Week",
    owner: "Roy Hunte",
    target: 5,
    actual: 9,
    trend: "up",
    week: "W1",
    frequency: "weekly",
    unit: "number",
    points: pts([
      ["Mar 9", 8], ["Mar 16", 6], ["Mar 23", 6], ["Mar 30", 8],
      ["Apr 6", 2], ["Apr 13", 6], ["Apr 20", 6], ["Apr 27", 5],
      ["May 4", 6], ["May 11", 2], ["May 18", 2], ["May 25", 5],
      ["Jun 1", 7], ["Jun 8", 9],
    ]),
  },
  {
    id: "k5",
    name: "Weekly Orders ≥$180",
    owner: "Elizabeth Ward",
    target: 150,
    actual: 91,
    trend: "up",
    week: "W1",
    frequency: "weekly",
    unit: "number",
    points: pts([
      ["Mar 9", 66], ["Mar 16", 110], ["Mar 23", 117], ["Mar 30", 114],
      ["Apr 6", 72], ["Apr 13", 92], ["Apr 20", 89], ["Apr 27", 107],
      ["May 4", 84], ["May 11", 90], ["May 18", 105], ["May 25", 77],
      ["Jun 1", 83], ["Jun 8", 91],
    ]),
  },
  {
    id: "k6",
    name: "Weekly Orders ≤$199",
    owner: "Elizabeth Ward",
    target: 75,
    actual: 67,
    trend: "down",
    week: "W1",
    frequency: "weekly",
    unit: "number",
    points: pts([
      ["Mar 9", 56], ["Mar 16", 102], ["Mar 23", 100], ["Mar 30", 98],
      ["Apr 6", 86], ["Apr 13", 77], ["Apr 20", 75], ["Apr 27", 86],
      ["May 4", 71], ["May 11", 83], ["May 18", 93], ["May 25", 82],
      ["Jun 1", 132], ["Jun 8", 67],
    ]),
  },
  {
    id: "k7",
    name: "Calls to Prospective Customers",
    owner: "Russell Hunte",
    target: 2,
    actual: 3,
    trend: "flat",
    week: "W1",
    frequency: "weekly",
    unit: "number",
    points: pts([
      ["Feb 9", 2], ["Feb 16", 3], ["Feb 23", 3], ["Mar 2", 2],
      ["Mar 9", 2], ["Mar 16", 0], ["Mar 23", 3], ["Mar 30", 2],
      ["Apr 6", 3], ["Apr 13", 3], ["Apr 20", 3], ["Apr 27", 3],
      ["May 4", 3], ["May 11", 3],
    ]),
  },
  {
    id: "k8",
    name: "Gross Profit Margin",
    owner: "Russell Hunte",
    target: 40,
    actual: 27.58,
    trend: "down",
    week: "W1",
    frequency: "weekly",
    unit: "percent",
    points: pts([
      ["Oct 6", 35.5], ["Oct 27", 59.6], ["Nov 17", 47.56], ["Dec 8", 57.6],
      ["Jan 5", 36.7], ["Jan 12", 38.4], ["Feb 2", 38.4], ["Feb 23", 35.16],
      ["Mar 1", 36], ["Mar 8", 33], ["Mar 15", 32], ["Mar 22", 40],
      ["Mar 29", 38], ["Apr 5", 27.58],
    ]),
  },
  {
    id: "k9",
    name: "Orders Shipped Within 6 Days",
    owner: "Russell Hunte",
    target: 66,
    actual: 60,
    trend: "flat",
    week: "W1",
    frequency: "weekly",
    unit: "percent",
    points: pts([
      ["Sep 7", 65], ["Oct 5", 70], ["Nov 2", 73], ["Nov 30", 78],
      ["Dec 28", 80], ["Jan 4", 75], ["Jan 11", 65], ["Jan 25", 66.7],
      ["Feb 8", 66], ["Feb 15", 63], ["Feb 22", 58], ["Mar 1", 60],
      ["Mar 8", 62], ["Mar 22", 60],
    ]),
  },
];

// ─── ROCKS / QUARTERLY PRIORITIES ────────────────────────────────────────────
export const seedRocks: Rock[] = [
  {
    id: "r1",
    title: "Focus on customer development: Enhance customer knowledge to facilitate the sale of higher-value products",
    owner: "Russell Hunte",
    dueDate: format(addDays(today, 30), "yyyy-MM-dd"),
    status: "Off Track",
    percentComplete: 25,
    notes: "Need to create customer education programme and visit top accounts",
    meetingId: "m1",
  },
  {
    id: "r2",
    title: "Work through 11 steps toward successful merger",
    owner: "Russell Hunte",
    dueDate: format(addDays(today, 60), "yyyy-MM-dd"),
    status: "Off Track",
    percentComplete: 20,
    notes: "Reviewing legal and financial requirements",
    meetingId: "m1",
  },
  {
    id: "r3",
    title: "Stop orders leaving with price errors",
    owner: "Roy Hunte",
    dueDate: format(addDays(today, 14), "yyyy-MM-dd"),
    status: "On Track",
    percentComplete: 70,
    notes: "Process created; continuing to monitor and train staff",
    meetingId: "m1",
  },
  {
    id: "r4",
    title: "Cross training for multiple roles among the staff",
    owner: "Randall Hunte",
    dueDate: format(addDays(today, 45), "yyyy-MM-dd"),
    status: "On Track",
    percentComplete: 40,
    notes: "Identifying key roles and scheduling cross-training sessions",
    meetingId: "m1",
  },
  {
    id: "r5",
    title: "New Lens Acquisition Strategy – source blanks from China",
    owner: "Russell Hunte",
    dueDate: format(addDays(today, 90), "yyyy-MM-dd"),
    status: "On Track",
    percentComplete: 30,
    notes: "Researching suppliers and cost comparisons",
    meetingId: "m2",
  },
  {
    id: "r6",
    title: "Get Gross Profit Margin consistently above 40%",
    owner: "Elizabeth Ward",
    dueDate: format(addDays(today, 60), "yyyy-MM-dd"),
    status: "Off Track",
    percentComplete: 15,
    notes: "Currently at 27.58% – need pricing review and cost reduction plan",
    meetingId: "m1",
  },
];

// ─── TODOS ────────────────────────────────────────────────────────────────────
export const seedTodos: Todo[] = [
  { id: "t1", title: "Document repetitive processes in admin", owner: "Elizabeth Ward", dueDate: format(addDays(today, 14), "yyyy-MM-dd"), completed: false, meetingId: "m1" },
  { id: "t2", title: "Discuss drivers to increase GP and how to measure them", owner: "Elizabeth Ward", dueDate: format(addDays(today, 7), "yyyy-MM-dd"), completed: false, meetingId: "m1" },
  { id: "t3", title: "Educate customers on selling higher value lenses", owner: "Russell Hunte", dueDate: format(addDays(today, 14), "yyyy-MM-dd"), completed: false, meetingId: "m1" },
  { id: "t4", title: "Update expected delivery / turnaround time in system", owner: "Russell Hunte", dueDate: format(addDays(today, 7), "yyyy-MM-dd"), completed: false, meetingId: "m1" },
  { id: "t5", title: "Create price increase document for clear lenses", owner: "Russell Hunte", dueDate: format(addDays(today, 10), "yyyy-MM-dd"), completed: false, meetingId: "m1" },
  { id: "t6", title: "Update pricing to latest increase in Precision Pricing", owner: "Russell Hunte", dueDate: format(addDays(today, 10), "yyyy-MM-dd"), completed: false, meetingId: "m1" },
  { id: "t7", title: "Review WIP tracking and process documentation", owner: "Roy Hunte", dueDate: format(addDays(today, 5), "yyyy-MM-dd"), completed: false, meetingId: "m1" },
  { id: "t8", title: "Schedule cross-training sessions for all roles", owner: "Randall Hunte", dueDate: format(addDays(today, 21), "yyyy-MM-dd"), completed: false, meetingId: "m3" },
  { id: "t9", title: "Pull monthly GP margin report", owner: "Elizabeth Ward", dueDate: format(addDays(today, 3), "yyyy-MM-dd"), completed: false, meetingId: "m1" },
  { id: "t10", title: "Investigate root cause of breakage spike", owner: "Roy Hunte", dueDate: format(addDays(today, 5), "yyyy-MM-dd"), completed: false, meetingId: "m1" },
];

// ─── ISSUES / IDS ─────────────────────────────────────────────────────────────
export const seedIssues: Issue[] = [
  {
    id: "i1",
    title: "Gross Profit Margin consistently below 40% target",
    owner: "Russell Hunte",
    priority: "High",
    status: "Open",
    identified: "GP margin at 27.58% – significantly below the 40% goal",
    discussed: "Review pricing strategy, reduce cost of goods, analyse product mix",
    solved: "",
    meetingId: "m1",
  },
  {
    id: "i2",
    title: "Breakages above target – 9 last week vs goal of ≤5",
    owner: "Roy Hunte",
    priority: "High",
    status: "Open",
    identified: "Quality control failures causing rework and waste",
    discussed: "Identify root causes; reinforce QC checks at each production stage",
    solved: "",
    meetingId: "m1",
  },
  {
    id: "i3",
    title: "Weekly orders valued ≥$180 below goal (91 vs 150)",
    owner: "Elizabeth Ward",
    priority: "Medium",
    status: "In Progress",
    identified: "Customers ordering lower-value products; missing revenue potential",
    discussed: "Customer education programme, sales training on higher-value lens positioning",
    solved: "",
    meetingId: "m1",
  },
  {
    id: "i4",
    title: "Orders shipped within 6 days below 66% target",
    owner: "Roy Hunte",
    priority: "Medium",
    status: "Open",
    identified: "Turnaround time slipping – currently at 60%",
    discussed: "Review production scheduling and priority job system",
    solved: "",
    meetingId: "m3",
  },
];

// ─── BUSINESS PLAN / VCP ──────────────────────────────────────────────────────
export const seedBusinessPlan: BusinessPlan = {
  futureFocus: {
    coreValues: [
      "Willing, available, helpful, proactive",
      "Dedicated, committed, industrious",
      "Reliable, accurate, attentive to detail, methodical, meticulous, precise",
      "Listener, easy to talk to, approachable, supportive",
      "Hungry for growth",
    ],
    bhag: "10x profit/sales – $10M in 10 years. Be the main supplier of quality lens and optical products in the Caribbean region, with 120+ customers, 80% production automation, and every employee earning a 6-figure salary.",
    threeYearVision: {
      revenue: "$3,200,000",
      mrr: "$267K/mo",
      nrr: "Target 40% GP",
      grossMargin: "40%+",
      customers: "120+ active accounts",
    },
    marketingStrategy: {
      targetMarket: "Optical practices and dispensing opticians across the Caribbean.",
      differentiators: "Focus on excellence in product quality and customer service. Personalized approach to customer support and business development. Comprehensive training and certification programmes to ensure customer success.",
      guarantee: "Improve life through better vision – consistently delivering quality lenses on time.",
      process: "Direct sales calls to current and prospective customers; convert via Lablink platform onboarding; grow through training and certifications.",
    },
    coreFocus: "We make lenses for glasses – improving life through better vision.",
    coachesAndAdvisors: "UBT Business Coaches (Charlene Krassoi & team), external accountant, legal advisors.",
    richNotes: "<p><strong>Value Creation Plan:</strong> Classic Visions is building toward being the leading optical lens lab in the Caribbean. Key priorities are improving GP margin, growing the customer base to 120+, automating 80% of production, and ensuring all team members earn a 6-figure salary.</p><p><strong>Winning Aspiration:</strong> Improving life through better vision.</p><p><strong>Point of Difference:</strong> Focus on excellence in product quality and customer service, with a personalized approach and comprehensive training programmes.</p>",
  },
  shortTermFocus: {
    oneYearPlan: "Reach $3.2M revenue with GP margin consistently above 40%. Grow to 120+ active customers. Launch the next phase of the Classic Visions website and business system.",
    quarterlyGoals: "Get GP margin above 40%. Reduce breakages to ≤5/week. Increase weekly orders consistently above 150. Advance customer development programme.",
    keyInitiatives: "Customer education programme for higher-value lenses. New lens acquisition strategy (blanks from China). Website and business system upgrade. Cross-training across all roles.",
    obstacles: "GP margin below target. Breakages above goal. Orders valued ≥$180 significantly below target. Turnaround time (6-day shipping) below 66%.",
    rocksSummary: "Customer development programme, merger steps, stop price errors, cross-training, lens acquisition strategy, GP margin recovery.",
    notes: "Review scorecard every weekly leadership meeting. All rocks reviewed every 90 days. Core values recognition in every all-team meeting.",
  },
};

// ─── SETTINGS ────────────────────────────────────────────────────────────────
export const seedSettings: MoonshotSettings = {
  organizationName: "Classic Visions",
  enableZapier: false,
  editOrgChartPermission: "admin",
  addUpgradeUsersPermission: "admin",
  editDeleteUsersPermission: "admin",
  managersAreAdmins: false,
  managerSeeOwnRocksAndKpisOnly: false,
  supervisorsEditAccountabilities: true,
  employeesEditAccountabilities: true,
  supervisorsRemoveUsers: false,
  supervisorsEditPositions: true,
  allowRapidFireAcrossMeetings: true,
  allowGoodNewsAcrossMeetings: true,
  allowAddingClientsAsUsers: false,
  sendEmailInvitationsByDefault: false,
  currentQuarter: "Q2 2026",
  timeZone: "(UTC-04:00) Atlantic Time (Barbados)",
  weekStart: "Sunday",
  dateFormat: "dd-mm-yyyy",
  numberFormat: "1,234,567.90",
  defaultActionEmailTime: "9 AM (AST)",
  scorecardPeriod: "Weekly",
};
