// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.0";

// src/lib/mcp/tools/whoami.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.0";
var whoami_default = defineTool({
  name: "whoami",
  title: "Who am I",
  description: "Return the signed-in Classic Visions user's id, email, and any roles.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated." }], isError: true };
    }
    const { createClient } = await import("npm:@supabase/supabase-js@^2.101.1");
    const supabase = createClient(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      {
        global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
        auth: { persistSession: false, autoRefreshToken: false }
      }
    );
    const userId = ctx.getUserId();
    const { data: roles } = await supabase.from("user_roles").select("role").eq("user_id", userId);
    const summary = {
      user_id: userId,
      email: ctx.getUserEmail(),
      roles: (roles ?? []).map((r) => r.role)
    };
    return {
      content: [{ type: "text", text: JSON.stringify(summary, null, 2) }],
      structuredContent: summary
    };
  }
});

// src/lib/mcp/tools/search-products.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.0";
import { z } from "npm:zod@^3.25.76";
var search_products_default = defineTool2({
  name: "search_products",
  title: "Search store products",
  description: "Search the Classic Visions public store catalog by name or description. Returns up to `limit` products.",
  inputSchema: {
    query: z.string().min(1).describe("Search text matched against product name/description."),
    limit: z.number().int().min(1).max(50).optional().describe("Max rows to return (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated." }], isError: true };
    }
    const { createClient } = await import("npm:@supabase/supabase-js@^2.101.1");
    const supabase = createClient(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      {
        global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
        auth: { persistSession: false, autoRefreshToken: false }
      }
    );
    const cap = limit ?? 10;
    const like = `%${query.replace(/[%_]/g, "")}%`;
    const { data, error } = await supabase.from("store_products").select("id,name,product_type,description").or(`name.ilike.${like},description.ilike.${like}`).limit(cap);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    const rows = data ?? [];
    return {
      content: [{ type: "text", text: JSON.stringify(rows, null, 2) }],
      structuredContent: { count: rows.length, results: rows }
    };
  }
});

// src/lib/mcp/tools/list-my-orders.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.0";
import { z as z2 } from "npm:zod@^3.25.76";
var list_my_orders_default = defineTool3({
  name: "list_my_orders",
  title: "List my orders",
  description: "List the signed-in user's Classic Visions orders (most recent first). RLS restricts results to the caller.",
  inputSchema: {
    limit: z2.number().int().min(1).max(50).optional().describe("Max orders to return (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated." }], isError: true };
    }
    const { createClient } = await import("npm:@supabase/supabase-js@^2.101.1");
    const supabase = createClient(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      {
        global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
        auth: { persistSession: false, autoRefreshToken: false }
      }
    );
    const { data, error } = await supabase.from("orders").select("id,status,total,currency,created_at").order("created_at", { ascending: false }).limit(limit ?? 10);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    const rows = data ?? [];
    return {
      content: [{ type: "text", text: JSON.stringify(rows, null, 2) }],
      structuredContent: { count: rows.length, orders: rows }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "dzsalnvmlvjoatryhqfz";
var mcp_default = defineMcp({
  name: "classic-visions-mcp",
  title: "Classic Visions",
  version: "0.1.0",
  instructions: "Tools for the Classic Visions optical platform. Callers act as their signed-in user; RLS restricts what each tool can read or write.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [whoami_default, search_products_default, list_my_orders_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
