-- Runtime website analytics tables for live admin dashboard metrics.

CREATE TABLE IF NOT EXISTS public.website_analytics_sessions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  visitor_id text NOT NULL,
  started_at timestamptz NOT NULL DEFAULT now(),
  last_seen_at timestamptz NOT NULL DEFAULT now(),
  landing_path text NOT NULL DEFAULT '/',
  pageview_count integer NOT NULL DEFAULT 1 CHECK (pageview_count >= 0),
  duration_seconds integer NOT NULL DEFAULT 0 CHECK (duration_seconds >= 0),
  engaged boolean NOT NULL DEFAULT false,
  is_returning_visitor boolean NOT NULL DEFAULT false,
  device_type text NOT NULL DEFAULT 'desktop',
  referrer_host text NOT NULL DEFAULT 'Direct',
  user_agent text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.website_analytics_pageviews (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id uuid NOT NULL REFERENCES public.website_analytics_sessions(id) ON DELETE CASCADE,
  visitor_id text NOT NULL,
  pathname text NOT NULL,
  referrer_host text NOT NULL DEFAULT 'Direct',
  device_type text NOT NULL DEFAULT 'desktop',
  occurred_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.website_analytics_web_vitals (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id uuid NOT NULL REFERENCES public.website_analytics_sessions(id) ON DELETE CASCADE,
  visitor_id text NOT NULL,
  pathname text NOT NULL,
  metric_id text NOT NULL,
  metric_name text NOT NULL,
  metric_value double precision NOT NULL,
  metric_delta double precision NOT NULL DEFAULT 0,
  metric_rating text NOT NULL DEFAULT 'unknown',
  device_type text NOT NULL DEFAULT 'desktop',
  occurred_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS website_analytics_sessions_started_at_idx
  ON public.website_analytics_sessions(started_at DESC);

CREATE INDEX IF NOT EXISTS website_analytics_sessions_visitor_id_idx
  ON public.website_analytics_sessions(visitor_id);

CREATE INDEX IF NOT EXISTS website_analytics_pageviews_occurred_at_idx
  ON public.website_analytics_pageviews(occurred_at DESC);

CREATE INDEX IF NOT EXISTS website_analytics_pageviews_pathname_idx
  ON public.website_analytics_pageviews(pathname);

CREATE INDEX IF NOT EXISTS website_analytics_web_vitals_occurred_at_idx
  ON public.website_analytics_web_vitals(occurred_at DESC);

CREATE INDEX IF NOT EXISTS website_analytics_web_vitals_metric_name_idx
  ON public.website_analytics_web_vitals(metric_name);

ALTER TABLE public.website_analytics_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.website_analytics_pageviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.website_analytics_web_vitals ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS website_analytics_sessions_insert_public ON public.website_analytics_sessions;
CREATE POLICY website_analytics_sessions_insert_public
  ON public.website_analytics_sessions
  FOR INSERT
  TO anon, authenticated
  WITH CHECK (true);

DROP POLICY IF EXISTS website_analytics_sessions_update_public ON public.website_analytics_sessions;
CREATE POLICY website_analytics_sessions_update_public
  ON public.website_analytics_sessions
  FOR UPDATE
  TO anon, authenticated
  USING (true)
  WITH CHECK (true);

DROP POLICY IF EXISTS website_analytics_sessions_select_authenticated ON public.website_analytics_sessions;
CREATE POLICY website_analytics_sessions_select_authenticated
  ON public.website_analytics_sessions
  FOR SELECT
  TO authenticated
  USING (true);

DROP POLICY IF EXISTS website_analytics_pageviews_insert_public ON public.website_analytics_pageviews;
CREATE POLICY website_analytics_pageviews_insert_public
  ON public.website_analytics_pageviews
  FOR INSERT
  TO anon, authenticated
  WITH CHECK (true);

DROP POLICY IF EXISTS website_analytics_pageviews_select_authenticated ON public.website_analytics_pageviews;
CREATE POLICY website_analytics_pageviews_select_authenticated
  ON public.website_analytics_pageviews
  FOR SELECT
  TO authenticated
  USING (true);

DROP POLICY IF EXISTS website_analytics_web_vitals_insert_public ON public.website_analytics_web_vitals;
CREATE POLICY website_analytics_web_vitals_insert_public
  ON public.website_analytics_web_vitals
  FOR INSERT
  TO anon, authenticated
  WITH CHECK (true);

DROP POLICY IF EXISTS website_analytics_web_vitals_select_authenticated ON public.website_analytics_web_vitals;
CREATE POLICY website_analytics_web_vitals_select_authenticated
  ON public.website_analytics_web_vitals
  FOR SELECT
  TO authenticated
  USING (true);

GRANT INSERT, UPDATE ON public.website_analytics_sessions TO anon, authenticated;
GRANT SELECT ON public.website_analytics_sessions TO authenticated;
GRANT INSERT ON public.website_analytics_pageviews TO anon, authenticated;
GRANT SELECT ON public.website_analytics_pageviews TO authenticated;
GRANT INSERT ON public.website_analytics_web_vitals TO anon, authenticated;
GRANT SELECT ON public.website_analytics_web_vitals TO authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated;
