-- Unified order dispatch: one order model, two transports, both order forms.
--
-- DRAFTED FOR REVIEW — not run. You run all migrations yourself.
--
-- Two things change here.
--
-- 1. Stock orders gain the same transport choice Rx orders already have.
--    rx_order_submissions got dispatch_provider in 20260811170000; without
--    the matching column on stock_order_submissions a stock order can only
--    ever leave through optilens-local, and the innovations-sync worker
--    would claim Gatekeeper-bound rows too. Both outboxes now carry
--    dispatch_provider and an allocated outbound order number, so the
--    Gatekeeper Edge Function and the office worker each take only their own
--    rows and every order has one identifier regardless of route.
--
-- 2. The Stock Order Builder sells what the website sells. Per Russell
--    (2026-08-12): the stock form offers the items published on the website
--    and their variants — not the raw Innova lens-family catalog. Pricing
--    follows the item, on the existing mechanism: the account's assigned
--    pricelist_versions document, catalog_type 'stock', row_type
--    'lens'/'supply'/'addon', item_id = the product's own uuid. That is the
--    same bucket the Stock Lens Prices editor already writes to (see
--    StockSkuPricingTab.tsx and docs/PRICING_WHICH_TABLE.md — read that
--    before touching any pricing table here). No new pricing table, and the
--    'stock_variant' row_type introduced by 20260811000000 is no longer used
--    by this path.
--
-- The Innova SKU comes off the website variant, which is where it already
-- lives: store_product_variants.opc_code for a non-chiral variant, or
-- metadata->'opc_by_eye'->>'left'/'right' for a chiral one (written by
-- src/features/store-variants/innovationsVariantImport.ts). Supplies and
-- add-ons fall back to their own sku column.
--
-- NOT executed against the live database. Column names are read from
-- src/integrations/supabase/types.ts and the migrations named above.

-- ── 1. Stock outbox: transport choice + outbound order number ─────────────
ALTER TABLE public.stock_order_submissions
  ADD COLUMN IF NOT EXISTS dispatch_provider text NOT NULL DEFAULT 'innovations',
  ADD COLUMN IF NOT EXISTS gatekeeper_order_id bigint GENERATED BY DEFAULT AS IDENTITY,
  ADD COLUMN IF NOT EXISTS receipt jsonb;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conrelid = 'public.stock_order_submissions'::regclass
      AND conname = 'stock_order_submissions_dispatch_provider_check'
  ) THEN
    ALTER TABLE public.stock_order_submissions
      ADD CONSTRAINT stock_order_submissions_dispatch_provider_check
      CHECK (dispatch_provider IN ('innovations', 'gatekeeper'));
  END IF;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS stock_order_submissions_gatekeeper_order_id_key
  ON public.stock_order_submissions (gatekeeper_order_id)
  WHERE gatekeeper_order_id IS NOT NULL;

-- The Gatekeeper sender flips 'claimed' -> 'submitted'; the stock outbox's
-- own vocabulary calls that terminal state 'released'. Allow both so one
-- result-recorder can serve both tables.
ALTER TABLE public.stock_order_submissions
  DROP CONSTRAINT IF EXISTS stock_order_submissions_status_check;
ALTER TABLE public.stock_order_submissions
  ADD CONSTRAINT stock_order_submissions_status_check
  CHECK (status IN ('staged','approved','claimed','released','submitted','failed','cancelled'));

-- ── 2. Website-item pricing for stock orders ──────────────────────────────
-- p_items shape (jsonb array):
--   { "product_type": "lens"|"supply"|"addon",
--     "product_id":   uuid,          -- lenses.id / supplies.id / addons.id
--     "variant_id":   uuid | null,   -- store_product_variants.id
--     "side":         "right"|"left"|"either",
--     "quantity":     int,
--     "customer_ref": text }
--
-- Prices are ALWAYS resolved here, never trusted from client input.
CREATE OR REPLACE FUNCTION public._price_stock_order_items(p_pricelist_version_id integer, p_items jsonb)
RETURNS TABLE (priced_items jsonb, order_total numeric)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_item jsonb;
  v_product_type text;
  v_product_id uuid;
  v_variant_id uuid;
  v_side text;
  v_quantity integer;
  v_name text;
  v_published boolean;
  v_product_sku text;
  v_variant record;
  v_sku text;
  v_source text;
  v_part_rx text;
  v_description text;
  v_unit_price numeric;
  v_lens_state text;
  v_priced_items jsonb := '[]'::jsonb;
  v_total numeric := 0;
BEGIN
  IF p_items IS NULL OR jsonb_array_length(p_items) = 0 THEN
    RAISE EXCEPTION 'A stock order needs at least one item.';
  END IF;

  FOR v_item IN SELECT * FROM jsonb_array_elements(p_items)
  LOOP
    -- Drafts staged before this migration keyed items on an Innova power row.
    -- Those can't be repriced against the website catalog, and silently
    -- guessing a product would ship the wrong thing.
    IF v_item ? 'power_row_id' AND NOT (v_item ? 'product_id') THEN
      RAISE EXCEPTION 'This draft was built with the previous stock catalog. Rebuild it from the website catalog before releasing.';
    END IF;

    v_product_type := v_item ->> 'product_type';
    v_product_id   := NULLIF(v_item ->> 'product_id', '')::uuid;
    v_variant_id   := NULLIF(v_item ->> 'variant_id', '')::uuid;
    v_side         := COALESCE(NULLIF(v_item ->> 'side', ''), 'either');
    v_quantity     := COALESCE((v_item ->> 'quantity')::int, 1);

    IF v_product_type NOT IN ('lens', 'supply', 'addon') OR v_product_id IS NULL THEN
      RAISE EXCEPTION 'Each stock order item needs a website product type and id.';
    END IF;
    IF v_quantity < 1 OR v_quantity > 99 THEN
      RAISE EXCEPTION 'Item quantity must be between 1 and 99.';
    END IF;

    -- Website publication is the availability rule for this form.
    IF v_product_type = 'lens' THEN
      SELECT l.name, l.show_on_website AND l.is_active, NULL::text
        INTO v_name, v_published, v_product_sku
      FROM public.lenses l WHERE l.id = v_product_id;
      v_source := 'FLENS';
      v_part_rx := 'Y';
    ELSIF v_product_type = 'supply' THEN
      SELECT s.name, s.show_on_website AND s.is_active, s.sku
        INTO v_name, v_published, v_product_sku
      FROM public.supplies s WHERE s.id = v_product_id;
      v_source := 'MISC';
      v_part_rx := 'N';
    ELSE
      SELECT a.name, a.show_on_website AND a.is_active, a.sku
        INTO v_name, v_published, v_product_sku
      FROM public.addons a WHERE a.id = v_product_id;
      -- An add-on's own name is the only signal for which Hashref item
      -- category it belongs to; anything unrecognised stays MISC.
      v_source := CASE
        WHEN v_name ~* 'tint|colou?r'                       THEN 'TINT'
        WHEN v_name ~* 'coat|anti[- ]?reflect|\mar\M|mirror' THEN 'COAT'
        WHEN v_name ~* 'edg(e|ing)|glaz'                    THEN 'EDGING'
        ELSE 'MISC'
      END;
      v_part_rx := 'Y';
    END IF;

    IF v_name IS NULL THEN
      RAISE EXCEPTION 'Unknown % product: %', v_product_type, v_product_id;
    END IF;
    IF NOT COALESCE(v_published, false) THEN
      RAISE EXCEPTION '"%" is not published on the website and cannot be ordered here.', v_name;
    END IF;

    SELECT MAX(r.bbd_price) INTO v_unit_price
    FROM public.pricelist_catalog_rows r
    WHERE r.pricelist_version_id = p_pricelist_version_id
      AND r.catalog_type = 'stock'
      AND r.row_type = v_product_type
      AND r.item_id = v_product_id
      AND r.bbd_price IS NOT NULL;

    IF v_unit_price IS NULL THEN
      RAISE EXCEPTION '"%" is not priced on this account''s pricelist.', v_name;
    END IF;

    v_description := v_name;
    v_sku := v_product_sku;

    IF v_variant_id IS NOT NULL THEN
      SELECT * INTO v_variant
      FROM public.store_product_variants pv
      WHERE pv.id = v_variant_id
        AND pv.product_type = v_product_type
        AND pv.product_id = v_product_id
        AND pv.is_active;
      IF NOT FOUND THEN
        RAISE EXCEPTION 'That variant of "%" is no longer available on the website.', v_name;
      END IF;

      -- A chiral variant carries one Innova code per eye; a symmetric one
      -- carries a single opc_code that serves both.
      v_sku := COALESCE(
        NULLIF(v_variant.metadata -> 'opc_by_eye' ->> v_side, ''),
        NULLIF(v_variant.opc_code, ''),
        NULLIF(v_variant.sku, ''),
        v_product_sku
      );
      v_description := v_name || ' ' || COALESCE(v_variant.title, '');
      IF v_side IN ('right', 'left') THEN
        v_description := v_description || ' / ' || v_side;
      END IF;

      IF v_product_type = 'lens' THEN
        SELECT sl.lens_state INTO v_lens_state
        FROM public.innovations_store_lens_power_rows pr
        JOIN public.innovations_store_lenses sl ON sl.innovations_lens_id = pr.innovations_lens_id
        WHERE pr.id = ((v_variant.metadata -> 'innovations_power_row_ids' ->> 0))::uuid;
        -- A website stock lens is a finished, stocked item unless Lens Local
        -- says the underlying family is semi-finished. Semi-finished blanks
        -- are normally the Rx path, so FLENS stays the default.
        IF v_lens_state = 'semi_finished' THEN v_source := 'SFLENS'; END IF;
      END IF;
    END IF;

    IF NULLIF(BTRIM(COALESCE(v_sku, '')), '') IS NULL THEN
      RAISE EXCEPTION '"%" has no Innova SKU to order with. Add its OPC code to the website variant first.', v_description;
    END IF;

    v_priced_items := v_priced_items || jsonb_build_object(
      'product_type', v_product_type,
      'product_id',   v_product_id,
      'variant_id',   v_variant_id,
      'side',         v_side,
      'sku',          v_sku,
      'source',       v_source,
      'description',  v_description,
      'quantity',     v_quantity,
      'comment',      COALESCE(v_item ->> 'customer_ref', ''),
      'part_rx',      v_part_rx,
      'item_side',    'NONE',
      'unit_price',   v_unit_price
    );
    v_total := v_total + v_unit_price * v_quantity;
  END LOOP;

  RETURN QUERY SELECT v_priced_items, v_total;
END;
$function$;

REVOKE ALL ON FUNCTION public._price_stock_order_items(integer, jsonb) FROM PUBLIC;

-- ── 3. Which accounts can build a stock order ─────────────────────────────
-- Same availability rule as before, retargeted at the website-item rows:
-- an account is eligible when its assigned pricelist document prices at
-- least one published website item in the 'stock' catalog.
DROP VIEW IF EXISTS public.stock_lens_eligible_accounts;
CREATE VIEW public.stock_lens_eligible_accounts
WITH (security_invoker = true) AS
SELECT DISTINCT c.id AS account_id, c.assigned_pricelist_id AS pricelist_version_id
FROM public.customers c
JOIN public.pricelist_catalog_rows r
  ON r.pricelist_version_id = c.assigned_pricelist_id
WHERE r.catalog_type = 'stock'
  AND r.row_type IN ('lens', 'supply', 'addon')
  AND r.item_id IS NOT NULL
  AND r.bbd_price IS NOT NULL;

GRANT SELECT ON public.stock_lens_eligible_accounts TO authenticated;

-- ── 4. The stock form's catalog ───────────────────────────────────────────
-- Website-published items, priced on this account's document. Variants come
-- from the website's own reader (get_store_product_variants_public), so the
-- form shows exactly the items and variants the storefront shows.
CREATE OR REPLACE FUNCTION public.get_stock_order_catalog(p_account_id integer)
RETURNS TABLE (
  product_type text,
  product_id uuid,
  name text,
  category text,
  sku text,
  unit_price numeric,
  has_variants boolean
)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_pricelist_version_id integer;
BEGIN
  IF NOT public.has_any_role(auth.uid()) THEN
    RAISE EXCEPTION 'Not authorized to read the stock order catalog.';
  END IF;

  SELECT assigned_pricelist_id INTO v_pricelist_version_id
  FROM public.customers WHERE id = p_account_id;
  IF v_pricelist_version_id IS NULL THEN RETURN; END IF;

  RETURN QUERY
  WITH priced AS (
    SELECT r.row_type, r.item_id, MAX(r.bbd_price) AS price
    FROM public.pricelist_catalog_rows r
    WHERE r.pricelist_version_id = v_pricelist_version_id
      AND r.catalog_type = 'stock'
      AND r.row_type IN ('lens', 'supply', 'addon')
      AND r.item_id IS NOT NULL
      AND r.bbd_price IS NOT NULL
    GROUP BY r.row_type, r.item_id
  ),
  variant_counts AS (
    SELECT pv.product_type AS ptype, pv.product_id AS pid, COUNT(*) AS n
    FROM public.store_product_variants pv
    WHERE pv.is_active
    GROUP BY pv.product_type, pv.product_id
  )
  SELECT 'lens'::text, l.id, l.name, 'Lens'::text, NULL::text, p.price,
         COALESCE(vc.n, 0) > 0
  FROM public.lenses l
  JOIN priced p ON p.row_type = 'lens' AND p.item_id = l.id
  LEFT JOIN variant_counts vc ON vc.ptype = 'lens' AND vc.pid = l.id
  WHERE l.show_on_website AND l.is_active
  UNION ALL
  SELECT 'supply'::text, s.id, s.name, s.category, s.sku, p.price,
         COALESCE(vc.n, 0) > 0
  FROM public.supplies s
  JOIN priced p ON p.row_type = 'supply' AND p.item_id = s.id
  LEFT JOIN variant_counts vc ON vc.ptype = 'supply' AND vc.pid = s.id
  WHERE s.show_on_website AND s.is_active
  UNION ALL
  SELECT 'addon'::text, a.id, a.name, COALESCE(a.category, 'Service'), a.sku, p.price,
         COALESCE(vc.n, 0) > 0
  FROM public.addons a
  JOIN priced p ON p.row_type = 'addon' AND p.item_id = a.id
  LEFT JOIN variant_counts vc ON vc.ptype = 'addon' AND vc.pid = a.id
  WHERE a.show_on_website AND a.is_active;
END;
$function$;

REVOKE ALL ON FUNCTION public.get_stock_order_catalog(integer) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_stock_order_catalog(integer) TO authenticated;

-- ── 5. Release gate: pick the transport, same as the Rx outbox ────────────
DROP FUNCTION IF EXISTS public.release_stock_order_submission(uuid);
CREATE FUNCTION public.release_stock_order_submission(
  p_id uuid,
  p_dispatch_provider text DEFAULT 'innovations'
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_account_id integer;
  v_raw_items jsonb;
  v_pricelist_version_id integer;
  v_priced jsonb;
  v_total numeric;
BEGIN
  IF NOT public.has_edit_role(auth.uid()) THEN
    RAISE EXCEPTION 'Only editors can release stock orders.';
  END IF;
  IF p_dispatch_provider NOT IN ('innovations', 'gatekeeper') THEN
    RAISE EXCEPTION 'Unsupported stock order provider.';
  END IF;

  SELECT account_id, payload -> 'raw_items'
  INTO v_account_id, v_raw_items
  FROM public.stock_order_submissions
  WHERE id = p_id AND status IN ('staged','failed');

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Submission not found or not in a releasable state.';
  END IF;

  SELECT assigned_pricelist_id INTO v_pricelist_version_id
  FROM public.customers WHERE id = v_account_id;

  IF v_pricelist_version_id IS NULL THEN
    RAISE EXCEPTION 'This account no longer has an assigned pricelist.';
  END IF;

  -- Reprice against the account's CURRENT pricelist so a price change
  -- between staging and release can't silently ship the old number.
  SELECT priced_items, order_total INTO v_priced, v_total
  FROM public._price_stock_order_items(v_pricelist_version_id, v_raw_items);

  UPDATE public.stock_order_submissions
  SET status = 'approved',
      dispatch_provider = p_dispatch_provider,
      approved_by = auth.uid(), approved_at = now(), last_error = NULL,
      payload = payload || jsonb_build_object('items', v_priced, 'order_total', v_total, 'repriced_at', now())
  WHERE id = p_id;
END;
$function$;

REVOKE ALL ON FUNCTION public.release_stock_order_submission(uuid, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.release_stock_order_submission(uuid, text) TO authenticated;

-- ── 6. One Gatekeeper result recorder for both outboxes ───────────────────
-- p_order_kind defaults to 'rx' so the existing named-argument call from
-- gatekeeper-orders keeps resolving while it is being redeployed.
DROP FUNCTION IF EXISTS public.record_gatekeeper_result(uuid, boolean, jsonb, text);
CREATE FUNCTION public.record_gatekeeper_result(
  p_submission_id uuid,
  p_success boolean,
  p_order_kind text DEFAULT 'rx',
  p_receipt jsonb DEFAULT NULL,
  p_error_message text DEFAULT NULL
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_receipt_id text;
  v_error text := LEFT(NULLIF(BTRIM(p_error_message), ''), 500);
BEGIN
  IF p_order_kind NOT IN ('rx', 'stock') THEN
    RAISE EXCEPTION 'Unsupported order kind.';
  END IF;
  v_receipt_id := COALESCE(p_receipt ->> 'id', p_receipt ->> 'requesting_id');

  IF p_order_kind = 'rx' THEN
    UPDATE public.rx_order_submissions
    SET status = CASE WHEN p_success THEN 'submitted' ELSE 'failed' END,
        transport = CASE WHEN p_success THEN 'gatekeeper' ELSE transport END,
        result_code = CASE WHEN v_receipt_id ~ '^[0-9]+$' AND v_receipt_id::bigint <= 2147483647 THEN v_receipt_id::integer ELSE NULL END,
        result_message = CASE WHEN p_success THEN 'Gatekeeper receipt accepted.' ELSE NULL END,
        rxt_data = CASE WHEN p_success THEN p_receipt::text ELSE NULL END,
        last_error = CASE WHEN p_success THEN NULL ELSE v_error END,
        submitted_at = CASE WHEN p_success THEN now() ELSE NULL END,
        attempts = attempts + 1,
        updated_at = now()
    WHERE id = p_submission_id AND status = 'claimed' AND dispatch_provider = 'gatekeeper';
  ELSE
    UPDATE public.stock_order_submissions
    SET status = CASE WHEN p_success THEN 'submitted' ELSE 'failed' END,
        transport = CASE WHEN p_success THEN 'gatekeeper' ELSE transport END,
        receipt = CASE WHEN p_success THEN p_receipt ELSE NULL END,
        last_error = CASE WHEN p_success THEN NULL ELSE v_error END,
        released_at = CASE WHEN p_success THEN now() ELSE NULL END,
        attempts = attempts + 1,
        updated_at = now()
    WHERE id = p_submission_id AND status = 'claimed' AND dispatch_provider = 'gatekeeper';
  END IF;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Gatekeeper submission was not claimed.';
  END IF;

  UPDATE public.gatekeeper_settings
  SET status = CASE WHEN p_success THEN 'connected' ELSE 'error' END,
      last_receipt_at = CASE WHEN p_success THEN now() ELSE last_receipt_at END,
      last_error = CASE WHEN p_success THEN NULL ELSE v_error END,
      updated_at = now()
  WHERE tenant_key = 'default';
END;
$function$;

REVOKE ALL ON FUNCTION public.record_gatekeeper_result(uuid, boolean, text, jsonb, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.record_gatekeeper_result(uuid, boolean, text, jsonb, text) TO service_role;

NOTIFY pgrst, 'reload schema';
