-- Datamation schema reconciliation.
-- Schema only: no data, storage objects, cron schedules, auth changes, or cutover.
BEGIN;
SET LOCAL lock_timeout = '10s';

-- Catalog and pricing.
CREATE TABLE IF NOT EXISTS public.catalog_templates (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name text NOT NULL,
  created_by text, cover_title text, cover_subtitle text,
  gradient_color_start text DEFAULT '#1e4db7', gradient_color_end text DEFAULT '#0f2a5e',
  created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now(),
  status text NOT NULL DEFAULT 'draft'
);
CREATE TABLE IF NOT EXISTS public.pricelist_versions (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name text NOT NULL,
  base_currency text DEFAULT 'BBD', is_template boolean DEFAULT false,
  markup_percent numeric DEFAULT 0, discount_percent numeric DEFAULT 0,
  created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now(),
  format_type text DEFAULT 'list', master_markup_percent numeric DEFAULT 0,
  master_discount_percent numeric DEFAULT 0
);
CREATE TABLE IF NOT EXISTS public.catalog_sections (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  catalog_template_id integer REFERENCES public.catalog_templates(id),
  section_type text NOT NULL, pricelist_version_id integer REFERENCES public.pricelist_versions(id),
  format_choice text DEFAULT 'list', article_id uuid REFERENCES public.help_articles(id),
  sort_order integer, is_included boolean DEFAULT true, custom_title text
);
CREATE TABLE IF NOT EXISTS public.catalog_assignments (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  catalog_template_id integer REFERENCES public.catalog_templates(id),
  customer_id integer, assigned_at timestamptz DEFAULT now()
);
CREATE TABLE IF NOT EXISTS public.catalog_pages (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  catalog_template_id integer NOT NULL REFERENCES public.catalog_templates(id),
  page_number integer NOT NULL DEFAULT 1, page_settings jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (catalog_template_id, page_number)
);
CREATE TABLE IF NOT EXISTS public.catalog_page_objects (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), page_id uuid NOT NULL REFERENCES public.catalog_pages(id),
  object_type text NOT NULL DEFAULT 'text', x numeric NOT NULL DEFAULT 0, y numeric NOT NULL DEFAULT 0,
  width numeric NOT NULL DEFAULT 200, height numeric, rotation numeric NOT NULL DEFAULT 0,
  z_index integer NOT NULL DEFAULT 0, content jsonb NOT NULL DEFAULT '{}'::jsonb,
  style jsonb NOT NULL DEFAULT '{}'::jsonb, is_locked boolean NOT NULL DEFAULT false,
  is_visible boolean NOT NULL DEFAULT true, label text,
  created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS public.material_upgrades (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, upgrade_name text NOT NULL, material text NOT NULL,
  full_price_bbd numeric, delta_bbd numeric, notes text, updated_at timestamptz DEFAULT now()
);
CREATE TABLE IF NOT EXISTS public.matrix_allocations (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pricelist_version_id integer REFERENCES public.pricelist_versions(id), treatment_type text NOT NULL,
  category text NOT NULL, material_index text NOT NULL, lens_id uuid REFERENCES public.lenses(id),
  allocated_price_bbd numeric, is_active boolean DEFAULT true, updated_at timestamptz DEFAULT now(),
  UNIQUE (pricelist_version_id, category, material_index, treatment_type)
);
CREATE TABLE IF NOT EXISTS public.price_matrix (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, category text NOT NULL UNIQUE,
  index_1_50 numeric, index_1_53 numeric, index_1_59 numeric, index_1_60 numeric,
  index_1_67 numeric, index_1_74 numeric, created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now()
);
CREATE TABLE IF NOT EXISTS public.pricelist_catalog_rows (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), pricelist_version_id integer NOT NULL REFERENCES public.pricelist_versions(id),
  catalog_type text NOT NULL DEFAULT 'rx', row_key text NOT NULL, row_type text NOT NULL, section text NOT NULL,
  display_description text NOT NULL DEFAULT '', bbd_price numeric, item_id uuid, sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (pricelist_version_id, catalog_type, row_key)
);
CREATE TABLE IF NOT EXISTS public.pricelist_child_sections (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pricelist_version_id integer REFERENCES public.pricelist_versions(id), section_type text NOT NULL,
  child_markup_percent numeric DEFAULT 0, child_discount_percent numeric DEFAULT 0,
  created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now()
);
CREATE TABLE IF NOT EXISTS public.pricelist_line_overrides (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  child_section_id integer REFERENCES public.pricelist_child_sections(id),
  reference_id text NOT NULL, reference_type text NOT NULL, overridden_price_bbd numeric, reason text,
  updated_at timestamptz DEFAULT now()
);
CREATE TABLE IF NOT EXISTS public.pricelist_notes (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, section text, content text, sort_order integer
);
CREATE TABLE IF NOT EXISTS public.pricelist_overrides (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pricelist_version_id integer REFERENCES public.pricelist_versions(id),
  category text, index_column text, overridden_price numeric, reason text, created_at timestamptz DEFAULT now()
);
CREATE TABLE IF NOT EXISTS public.rx_price_groupings (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, key text NOT NULL UNIQUE, default_name text NOT NULL,
  sort_order integer NOT NULL DEFAULT 0, is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS public.rx_price_categories (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, grouping_id integer NOT NULL REFERENCES public.rx_price_groupings(id),
  key text NOT NULL, default_name text NOT NULL, sort_order integer NOT NULL DEFAULT 0, is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(grouping_id, key)
);
CREATE TABLE IF NOT EXISTS public.rx_price_grouping_versions (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, pricelist_version_id integer NOT NULL REFERENCES public.pricelist_versions(id),
  grouping_id integer NOT NULL REFERENCES public.rx_price_groupings(id), display_name text, sort_order integer,
  is_enabled boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(pricelist_version_id, grouping_id)
);
CREATE TABLE IF NOT EXISTS public.rx_price_category_versions (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, pricelist_version_id integer NOT NULL REFERENCES public.pricelist_versions(id),
  category_id integer NOT NULL REFERENCES public.rx_price_categories(id), display_name text, sort_order integer,
  is_enabled boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(pricelist_version_id, category_id)
);

-- Customer, ERP read-model, API-key, and gateway schema.
CREATE TABLE IF NOT EXISTS public.customers (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name text NOT NULL, type text DEFAULT 'Customer',
  address text, email text UNIQUE, phone text, assigned_pricelist_id integer REFERENCES public.pricelist_versions(id),
  pipeline_stage text DEFAULT 'Prospect', notes text, created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now(),
  contact_id uuid REFERENCES public.contacts(id), innovations_customer_id bigint UNIQUE, account_number text,
  country_code text, credit_limit numeric, pay_by_card boolean, pay_by_eft boolean,
  eft_institution_name text, default_payment_type smallint
);
CREATE UNIQUE INDEX IF NOT EXISTS customers_account_number_key ON public.customers(account_number)
  WHERE account_number IS NOT NULL AND account_number <> '';
CREATE TABLE IF NOT EXISTS public.balances (
  innovations_customer_id integer PRIMARY KEY, customer_id integer REFERENCES public.customers(id), account_number text,
  credit_limit numeric, current_balance numeric, last_statement_amount numeric, last_statement_date date,
  last_payment_amount numeric, last_payment_date date, synced_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS balances_customer_id_idx ON public.balances(customer_id);
CREATE TABLE IF NOT EXISTS public.bank_payment_portals (
  bank_name text PRIMARY KEY, portal_url text, notes text, updated_at timestamptz NOT NULL DEFAULT now(),
  innovations_eft_institution_id bigint UNIQUE
);
CREATE TABLE IF NOT EXISTS public.statements (
  id bigint PRIMARY KEY, innovations_statement_id integer NOT NULL UNIQUE, innovations_customer_id integer NOT NULL,
  customer_id integer REFERENCES public.customers(id), account_number text, from_date date, to_date date, statement_date date,
  due_date date, opening_balance numeric, closing_balance numeric, payments numeric, finance_charges numeric,
  discount numeric, aging_amount_1 numeric, aging_amount_2 numeric, aging_amount_3 numeric, aging_amount_4 numeric,
  status smallint, void boolean NOT NULL DEFAULT false, printed boolean NOT NULL DEFAULT false,
  innovations_emailed boolean NOT NULL DEFAULT false, portal_emailed_at timestamptz,
  synced_at timestamptz NOT NULL DEFAULT now(), created_at timestamptz NOT NULL DEFAULT now(),
  transactions numeric, allowance numeric, volume_discount numeric
);
CREATE INDEX IF NOT EXISTS statements_customer_id_idx ON public.statements(customer_id);
CREATE TABLE IF NOT EXISTS public.statement_lines (
  id bigint PRIMARY KEY, innovations_statement_item_id integer NOT NULL UNIQUE,
  innovations_statement_id integer NOT NULL REFERENCES public.statements(innovations_statement_id),
  order_type smallint, invoice_id integer, reference text, patient text, post_date date, amount numeric,
  synced_at timestamptz NOT NULL DEFAULT now(), created_at timestamptz NOT NULL DEFAULT now(),
  order_id bigint, payment_method text, order_type_name text
);
CREATE TABLE IF NOT EXISTS public.api_keys (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text NOT NULL, key_prefix text NOT NULL, key_hash text NOT NULL UNIQUE,
  scopes text[] NOT NULL DEFAULT '{}'::text[], created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  last_used_at timestamptz, expires_at timestamptz, revoked_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
  draft_pricelist_version_id integer REFERENCES public.pricelist_versions(id) ON DELETE SET NULL
);
CREATE TABLE IF NOT EXISTS public.api_audit_log (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), api_key_id uuid REFERENCES public.api_keys(id) ON DELETE SET NULL,
  method text NOT NULL, resource text NOT NULL, resource_id text, status integer NOT NULL,
  request_summary jsonb DEFAULT '{}'::jsonb, response_summary jsonb DEFAULT '{}'::jsonb, ip text,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS public.live_data_gateway_agents (
  api_key_id uuid PRIMARY KEY REFERENCES public.api_keys(id) ON DELETE CASCADE,
  agent_name text NOT NULL DEFAULT 'OptiLens Local', agent_version text, capabilities text[] NOT NULL DEFAULT '{}'::text[],
  connected_at timestamptz NOT NULL DEFAULT now(), last_seen_at timestamptz NOT NULL DEFAULT now(), last_error text
);
CREATE TABLE IF NOT EXISTS public.live_data_gateway_requests (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), requested_by uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  website_customer_id bigint NOT NULL REFERENCES public.customers(id) ON DELETE CASCADE,
  source text NOT NULL, operation text NOT NULL, target jsonb NOT NULL DEFAULT '{}'::jsonb,
  arguments jsonb NOT NULL DEFAULT '{}'::jsonb, status text NOT NULL DEFAULT 'pending',
  claimed_by uuid REFERENCES public.api_keys(id) ON DELETE SET NULL, response_payload jsonb,
  error_code text, error_message text, requested_at timestamptz NOT NULL DEFAULT now(),
  claimed_at timestamptz, completed_at timestamptz, consumed_at timestamptz,
  expires_at timestamptz NOT NULL DEFAULT now() + interval '30 seconds',
  purge_after timestamptz NOT NULL DEFAULT now() + interval '5 minutes'
);
CREATE INDEX IF NOT EXISTS live_data_gateway_requests_pending_idx ON public.live_data_gateway_requests(status, requested_at)
  WHERE status = 'pending';
CREATE TABLE IF NOT EXISTS public.innovations_sync_runs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), entity text NOT NULL, api_key_id uuid REFERENCES public.api_keys(id),
  dry_run boolean NOT NULL DEFAULT true, received integer NOT NULL DEFAULT 0, upserted integer NOT NULL DEFAULT 0,
  failed integer NOT NULL DEFAULT 0, status text NOT NULL DEFAULT 'success', error_summary text,
  started_at timestamptz NOT NULL DEFAULT now(), finished_at timestamptz NOT NULL DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS public.innovations_sync_dead_letters (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), entity text NOT NULL, external_id text,
  api_key_id uuid REFERENCES public.api_keys(id), last_error text, source_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  status text NOT NULL DEFAULT 'pending', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now()
);

-- CRM and store variants.
CREATE TABLE IF NOT EXISTS public.crm_pipelines (
  key text PRIMARY KEY, label text NOT NULL, is_active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS public.cadences (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text NOT NULL, pipeline text NOT NULL REFERENCES public.crm_pipelines(key),
  target_stage text, description text, is_active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS public.cadence_steps (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), cadence_id uuid NOT NULL REFERENCES public.cadences(id) ON DELETE CASCADE,
  step_order integer NOT NULL, channel text NOT NULL, delay_days integer NOT NULL DEFAULT 0, subject text, body_template text,
  UNIQUE(cadence_id, step_order)
);
CREATE TABLE IF NOT EXISTS public.cadence_enrollments (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), contact_id uuid NOT NULL REFERENCES public.contacts(id) ON DELETE CASCADE,
  cadence_id uuid NOT NULL REFERENCES public.cadences(id) ON DELETE CASCADE, status text NOT NULL DEFAULT 'active',
  current_step integer NOT NULL DEFAULT 0, next_step_due_at timestamptz, enrolled_at timestamptz NOT NULL DEFAULT now(), completed_at timestamptz
);
CREATE TABLE IF NOT EXISTS public.order_activity (
  innovations_customer_id bigint PRIMARY KEY, contact_id uuid REFERENCES public.contacts(id) ON DELETE SET NULL,
  last_order_date date, orders_last_7_days integer NOT NULL DEFAULT 0, orders_last_30_days integer NOT NULL DEFAULT 0,
  orders_last_90_days integer NOT NULL DEFAULT 0, avg_gap_days numeric, synced_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS public.outreach_outbox (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), contact_id uuid NOT NULL REFERENCES public.contacts(id) ON DELETE CASCADE,
  enrollment_id uuid REFERENCES public.cadence_enrollments(id) ON DELETE SET NULL, channel text NOT NULL,
  subject text, body text, attachments jsonb NOT NULL DEFAULT '[]'::jsonb, status text NOT NULL DEFAULT 'draft',
  generated_by text NOT NULL DEFAULT 'ai', error text, created_at timestamptz NOT NULL DEFAULT now(),
  approved_at timestamptz, sent_at timestamptz
);
CREATE TABLE IF NOT EXISTS public.product_variants (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), product_type text NOT NULL, product_id uuid NOT NULL,
  variant_mode text NOT NULL DEFAULT 'none', variant_key text NOT NULL, title text NOT NULL, display_label text,
  sku text, opc_code text, price numeric NOT NULL DEFAULT 0, cost numeric, stock_qty integer,
  low_stock_threshold integer NOT NULL DEFAULT 5, allow_backorder boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT true, sort_order integer NOT NULL DEFAULT 0,
  attribute_values jsonb NOT NULL DEFAULT '{}'::jsonb, metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(product_type, product_id, variant_key)
);
CREATE TABLE IF NOT EXISTS public.store_product_media (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), product_type text NOT NULL, product_id uuid NOT NULL, image_url text NOT NULL,
  sort_order integer NOT NULL DEFAULT 0, is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS public.store_product_overrides (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), product_type text NOT NULL, product_id uuid NOT NULL,
  is_vat_taxable boolean NOT NULL DEFAULT false, quantity_label text, website_badges jsonb NOT NULL DEFAULT '[]'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(product_type, product_id)
);
CREATE TABLE IF NOT EXISTS public.pricelists (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), kind text NOT NULL, customer_id integer REFERENCES public.customers(id) ON DELETE CASCADE,
  name text, created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS public.pricelist_lines (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), pricelist_id uuid NOT NULL REFERENCES public.pricelists(id) ON DELETE CASCADE,
  item_ref uuid NOT NULL REFERENCES public.pricing_items(id), custom_price numeric NOT NULL, reason text,
  source text NOT NULL DEFAULT 'manual', created_by uuid REFERENCES auth.users(id), approved_by uuid REFERENCES auth.users(id),
  created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(pricelist_id, item_ref)
);

-- Source columns missing from existing target relations. Avoid NOT NULL on pre-existing rows.
ALTER TABLE public.activities ADD COLUMN IF NOT EXISTS type text, ADD COLUMN IF NOT EXISTS content text;
ALTER TABLE public.cart_items ADD COLUMN IF NOT EXISTS sku text, ADD COLUMN IF NOT EXISTS opc_code text,
  ADD COLUMN IF NOT EXISTS variant_snapshot jsonb DEFAULT '{}'::jsonb;
ALTER TABLE public.contacts ADD COLUMN IF NOT EXISTS is_customer boolean, ADD COLUMN IF NOT EXISTS lead_source text,
  ADD COLUMN IF NOT EXISTS pipeline_stage text, ADD COLUMN IF NOT EXISTS type text, ADD COLUMN IF NOT EXISTS business_name text,
  ADD COLUMN IF NOT EXISTS address text, ADD COLUMN IF NOT EXISTS facebook_page_id text, ADD COLUMN IF NOT EXISTS lead_score integer,
  ADD COLUMN IF NOT EXISTS innovations_contact_id bigint, ADD COLUMN IF NOT EXISTS innovations_parent_customer_id bigint,
  ADD COLUMN IF NOT EXISTS linked_customer_id bigint, ADD COLUMN IF NOT EXISTS pipeline text, ADD COLUMN IF NOT EXISTS stage text,
  ADD COLUMN IF NOT EXISTS stage_entered_at timestamptz, ADD COLUMN IF NOT EXISTS next_action_at timestamptz;
ALTER TABLE public.help_articles ADD COLUMN IF NOT EXISTS is_public boolean DEFAULT false;
ALTER TABLE public.helpdesk_ticket_review_queue_items ADD COLUMN IF NOT EXISTS resolved_at timestamptz,
  ADD COLUMN IF NOT EXISTS resolved_by uuid;
ALTER TABLE public.lead_audits ADD COLUMN IF NOT EXISTS generated_at timestamptz, ADD COLUMN IF NOT EXISTS pdf_url text,
  ADD COLUMN IF NOT EXISTS summary text;
ALTER TABLE public.lenses ADD COLUMN IF NOT EXISTS pricing_category text, ADD COLUMN IF NOT EXISTS pricing_index text;
ALTER TABLE public.notes ADD COLUMN IF NOT EXISTS is_ai_generated boolean DEFAULT false;
ALTER TABLE public.opportunities ADD COLUMN IF NOT EXISTS status text, ADD COLUMN IF NOT EXISTS expected_value numeric,
  ADD COLUMN IF NOT EXISTS close_date date, ADD COLUMN IF NOT EXISTS source text, ADD COLUMN IF NOT EXISTS audit_pdf_url text;
ALTER TABLE public.order_items ADD COLUMN IF NOT EXISTS sku text, ADD COLUMN IF NOT EXISTS opc_code text,
  ADD COLUMN IF NOT EXISTS variant_snapshot jsonb DEFAULT '{}'::jsonb;
ALTER TABLE public.price_catalog ADD COLUMN IF NOT EXISTS product_id uuid, ADD COLUMN IF NOT EXISTS web_price numeric;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS email text, ADD COLUMN IF NOT EXISTS email_verified_at timestamptz,
  ADD COLUMN IF NOT EXISTS profile_completed_at timestamptz, ADD COLUMN IF NOT EXISTS portal_access_status text,
  ADD COLUMN IF NOT EXISTS portal_access_note text, ADD COLUMN IF NOT EXISTS portal_access_approved_override boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS portal_access_approved_note text;

-- RLS and the least-privilege source-compatible access patterns needed before data import.
DO $$
DECLARE
  table_name text;
BEGIN
  FOREACH table_name IN ARRAY ARRAY[
    'catalog_templates', 'catalog_sections', 'catalog_assignments', 'catalog_pages',
    'catalog_page_objects', 'material_upgrades', 'matrix_allocations', 'price_matrix',
    'pricelist_catalog_rows', 'pricelist_child_sections', 'pricelist_line_overrides', 'pricelist_notes',
    'pricelist_overrides', 'pricelist_versions', 'pricelists', 'pricelist_lines',
    'rx_price_groupings', 'rx_price_categories', 'rx_price_grouping_versions', 'rx_price_category_versions',
    'customers', 'balances', 'bank_payment_portals', 'statements', 'statement_lines',
    'api_keys', 'api_audit_log', 'live_data_gateway_agents', 'live_data_gateway_requests',
    'innovations_sync_runs', 'innovations_sync_dead_letters', 'crm_pipelines', 'cadences',
    'cadence_steps', 'cadence_enrollments', 'order_activity', 'outreach_outbox',
    'product_variants', 'store_product_media', 'store_product_overrides'
  ]
  LOOP
    EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', table_name);
  END LOOP;
END $$;

CREATE POLICY "Staff manage catalog templates" ON public.catalog_templates FOR ALL TO authenticated
  USING (has_edit_role(auth.uid())) WITH CHECK (has_edit_role(auth.uid()));
CREATE POLICY "Staff manage catalog sections" ON public.catalog_sections FOR ALL TO authenticated
  USING (has_edit_role(auth.uid())) WITH CHECK (has_edit_role(auth.uid()));
CREATE POLICY "Staff manage catalog assignments" ON public.catalog_assignments FOR ALL TO authenticated
  USING (has_edit_role(auth.uid())) WITH CHECK (has_edit_role(auth.uid()));
CREATE POLICY "Staff manage catalog pages" ON public.catalog_pages FOR ALL TO authenticated
  USING (has_edit_role(auth.uid())) WITH CHECK (has_edit_role(auth.uid()));
CREATE POLICY "Staff manage catalog page objects" ON public.catalog_page_objects FOR ALL TO authenticated
  USING (has_edit_role(auth.uid())) WITH CHECK (has_edit_role(auth.uid()));
CREATE POLICY "Staff manage pricing reconciliation" ON public.pricelist_versions FOR ALL TO authenticated
  USING (has_edit_role(auth.uid())) WITH CHECK (has_edit_role(auth.uid()));
CREATE POLICY "Staff manage pricing matrix" ON public.matrix_allocations FOR ALL TO authenticated
  USING (has_edit_role(auth.uid())) WITH CHECK (has_edit_role(auth.uid()));
CREATE POLICY "Staff manage price matrix" ON public.price_matrix FOR ALL TO authenticated
  USING (has_edit_role(auth.uid())) WITH CHECK (has_edit_role(auth.uid()));
CREATE POLICY "Staff manage catalog pricing rows" ON public.pricelist_catalog_rows FOR ALL TO authenticated
  USING (has_edit_role(auth.uid())) WITH CHECK (has_edit_role(auth.uid()));
CREATE POLICY "Staff manage CRM cadences" ON public.cadences FOR ALL TO authenticated
  USING (has_edit_role(auth.uid())) WITH CHECK (has_edit_role(auth.uid()));
CREATE POLICY "Staff manage CRM cadence steps" ON public.cadence_steps FOR ALL TO authenticated
  USING (has_edit_role(auth.uid())) WITH CHECK (has_edit_role(auth.uid()));
CREATE POLICY "Staff manage CRM enrollments" ON public.cadence_enrollments FOR ALL TO authenticated
  USING (has_edit_role(auth.uid())) WITH CHECK (has_edit_role(auth.uid()));
CREATE POLICY "Staff manage outreach outbox" ON public.outreach_outbox FOR ALL TO authenticated
  USING (has_edit_role(auth.uid())) WITH CHECK (has_edit_role(auth.uid()));
CREATE POLICY "Staff manage product variants" ON public.product_variants FOR ALL TO authenticated
  USING (has_edit_role(auth.uid())) WITH CHECK (has_edit_role(auth.uid()));
CREATE POLICY "Staff manage product media" ON public.store_product_media FOR ALL TO authenticated
  USING (has_edit_role(auth.uid())) WITH CHECK (has_edit_role(auth.uid()));
CREATE POLICY "Staff manage product overrides" ON public.store_product_overrides FOR ALL TO authenticated
  USING (has_edit_role(auth.uid())) WITH CHECK (has_edit_role(auth.uid()));
CREATE POLICY "Admins manage API keys" ON public.api_keys FOR ALL TO authenticated
  USING (has_role(auth.uid(), 'admin'::app_role)) WITH CHECK (has_role(auth.uid(), 'admin'::app_role));
CREATE POLICY "Admins read API audit log" ON public.api_audit_log FOR SELECT TO authenticated
  USING (has_role(auth.uid(), 'admin'::app_role));
CREATE POLICY "Customers read own statements" ON public.statements FOR SELECT TO authenticated
  USING (customer_id IN (SELECT crm_customer_id FROM public.profiles WHERE user_id = auth.uid()));
CREATE POLICY "Customers read own statement lines" ON public.statement_lines FOR SELECT TO authenticated
  USING (innovations_statement_id IN (
    SELECT innovations_statement_id FROM public.statements WHERE customer_id IN
      (SELECT crm_customer_id FROM public.profiles WHERE user_id = auth.uid())
  ));
CREATE POLICY "Staff read statements" ON public.statements FOR SELECT TO authenticated USING (has_edit_role(auth.uid()));
CREATE POLICY "Staff read statement lines" ON public.statement_lines FOR SELECT TO authenticated USING (has_edit_role(auth.uid()));
CREATE POLICY "Staff read balances" ON public.balances FOR SELECT TO authenticated USING (has_edit_role(auth.uid()));
CREATE POLICY "Authenticated read bank payment portals" ON public.bank_payment_portals FOR SELECT TO authenticated USING (true);
CREATE POLICY "Staff write bank payment portals" ON public.bank_payment_portals FOR ALL TO authenticated
  USING (has_edit_role(auth.uid())) WITH CHECK (has_edit_role(auth.uid()));

-- Secure R1 views.
CREATE OR REPLACE VIEW public.catalog_live AS
  SELECT l.id, 'lens'::text AS product_type, l.id AS product_id, NULL::text AS sku, l.name,
    l.pricing_category AS category, l.supplier_id, s.name AS supplier_name, l.base_price AS cost,
    l.sell_price, 'USD'::text AS currency, l.show_on_website AS web_enabled,
    l.show_in_ws_pricelist AS wspl_enabled, l.is_active, l.created_at, l.updated_at,
    lt.name AS lenstype, m.name AS material, mf.name AS mftype
  FROM public.lenses l LEFT JOIN public.suppliers s ON s.id = l.supplier_id
    LEFT JOIN public.lenstypes lt ON lt.id = l.lenstype_id
    LEFT JOIN public.materials m ON m.id = l.material_id
    LEFT JOIN public.mftypes mf ON mf.id = l.mftype_id WHERE l.is_active
  UNION ALL
  SELECT sp.id, 'supply'::text, sp.id, sp.sku, sp.name, sp.category, sp.supplier_id, s.name,
    sp.base_price, sp.sell_price, COALESCE(sp.currency, 'USD'), sp.show_on_website, sp.stk_wspl,
    sp.is_active, sp.created_at, sp.updated_at, NULL::text, NULL::text, NULL::text
  FROM public.supplies sp LEFT JOIN public.suppliers s ON s.id = sp.supplier_id WHERE sp.is_active
  UNION ALL
  SELECT a.id, 'addon'::text, a.id, a.sku, a.name, a.category, a.supplier_id, s.name,
    a.cost, a.price, 'USD'::text, a.show_on_website, false, a.is_active, a.created_at, a.updated_at,
    NULL::text, NULL::text, NULL::text
  FROM public.addons a LEFT JOIN public.suppliers s ON s.id = a.supplier_id WHERE a.is_active;
REVOKE ALL ON public.catalog_live FROM anon, authenticated, PUBLIC;
GRANT SELECT ON public.catalog_live TO service_role;

CREATE OR REPLACE VIEW public.balances_public WITH (security_invoker = true) AS
  SELECT customer_id, account_number, credit_limit, current_balance, last_statement_amount,
    last_statement_date, last_payment_amount, last_payment_date, synced_at FROM public.balances;
CREATE OR REPLACE VIEW public.statements_public WITH (security_invoker = true) AS
  SELECT id::text AS id, customer_id, account_number, from_date AS period_start, to_date AS period_end,
    opening_balance, closing_balance, payments, finance_charges, discount, due_date, status, void, printed,
    innovations_emailed, portal_emailed_at, synced_at FROM public.statements;
CREATE OR REPLACE VIEW public.statement_lines_public WITH (security_invoker = true) AS
  SELECT sl.id, sl.innovations_statement_id::text AS statement_id, s.customer_id, s.account_number,
    sl.order_type, sl.invoice_id, sl.reference, sl.patient, sl.post_date, sl.amount
  FROM public.statement_lines sl JOIN public.statements s ON s.innovations_statement_id = sl.innovations_statement_id;
CREATE OR REPLACE VIEW public.customer_account_number_duplicates WITH (security_invoker = true) AS
  SELECT account_number, count(*) AS duplicate_count, array_agg(id ORDER BY id) AS customer_ids,
    array_agg(name ORDER BY id) AS customer_names
  FROM public.customers WHERE account_number IS NOT NULL AND btrim(account_number) <> ''
  GROUP BY account_number HAVING count(*) > 1;
CREATE OR REPLACE VIEW public.customer_payment_profile_public WITH (security_invoker = true) AS
  SELECT id AS customer_id, account_number, name, pay_by_card, pay_by_eft, eft_institution_name, default_payment_type
  FROM public.customers;
CREATE OR REPLACE VIEW public.customer_order_health WITH (security_invoker = true) AS
  SELECT c.id AS contact_id, c.name, c.pipeline, c.stage, oa.last_order_date,
    current_date - oa.last_order_date AS quiet_days, oa.avg_gap_days, oa.orders_last_30_days,
    CASE WHEN oa.last_order_date IS NULL THEN 'unknown'
      WHEN current_date - oa.last_order_date >= 21 THEN 'alarm'
      WHEN current_date - oa.last_order_date >= 14 THEN 'flag' ELSE 'ok' END AS health
  FROM public.contacts c JOIN public.order_activity oa ON oa.contact_id = c.id WHERE c.stage = 'customer';
CREATE OR REPLACE VIEW public.store_product_variants_public WITH (security_invoker = true) AS
  SELECT id, product_type, product_id, title, variant_key, sku, opc_code, attribute_values AS attributes,
    metadata, price, stock_qty, 0::integer AS reserved_qty, low_stock_threshold, allow_backorder,
    is_active, sort_order, created_at, updated_at FROM public.product_variants WHERE is_active = true;
REVOKE ALL ON public.balances_public, public.statements_public, public.statement_lines_public,
  public.customer_account_number_duplicates, public.customer_payment_profile_public FROM anon, PUBLIC;
GRANT SELECT ON public.balances_public, public.statements_public, public.statement_lines_public,
  public.customer_account_number_duplicates, public.customer_payment_profile_public TO authenticated, service_role;
GRANT SELECT ON public.store_product_variants_public TO anon, authenticated;

-- Empty bucket definitions and source-equivalent storage write policy scope.
INSERT INTO storage.buckets (id, name, public) VALUES
  ('catalog-assets', 'catalog-assets', true), ('data-files', 'data-files', false),
  ('docs', 'docs', false), ('product-images', 'product-images', true),
  ('zenvue-branding', 'zenvue-branding', true)
ON CONFLICT (id) DO UPDATE SET public = EXCLUDED.public;
CREATE POLICY "catalog assets editor write" ON storage.objects FOR ALL TO authenticated
  USING (bucket_id = 'catalog-assets' AND has_edit_role(auth.uid()))
  WITH CHECK (bucket_id = 'catalog-assets' AND has_edit_role(auth.uid()));
CREATE POLICY "data files editor write" ON storage.objects FOR ALL TO authenticated
  USING (bucket_id = 'data-files' AND has_edit_role(auth.uid()))
  WITH CHECK (bucket_id = 'data-files' AND has_edit_role(auth.uid()));
CREATE POLICY "docs editor write" ON storage.objects FOR ALL TO authenticated
  USING (bucket_id = 'docs' AND has_edit_role(auth.uid()))
  WITH CHECK (bucket_id = 'docs' AND has_edit_role(auth.uid()));
CREATE POLICY "product images editor write" ON storage.objects FOR ALL TO authenticated
  USING (bucket_id = 'product-images' AND has_edit_role(auth.uid()))
  WITH CHECK (bucket_id = 'product-images' AND has_edit_role(auth.uid()));
CREATE POLICY "product images public read" ON storage.objects FOR SELECT TO public
  USING (bucket_id = 'product-images');
CREATE POLICY "zenvue branding editor write" ON storage.objects FOR ALL TO authenticated
  USING (bucket_id = 'zenvue-branding' AND has_edit_role(auth.uid()))
  WITH CHECK (bucket_id = 'zenvue-branding' AND has_edit_role(auth.uid()));

NOTIFY pgrst, 'reload schema';
COMMIT;
