// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { isPortalEmulationTab } from '@/lib/portalEmulation';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

const createMemoryStorage = () => {
  const store = new Map<string, string>();

  return {
    getItem: (key: string) => store.get(key) ?? null,
    setItem: (key: string, value: string) => {
      store.set(key, value);
    },
    removeItem: (key: string) => {
      store.delete(key);
    },
  };
};

const resolvedStorage = (() => {
  if (typeof window === "undefined" || !("localStorage" in window)) {
    return createMemoryStorage();
  }

  // An admin "signed in as customer" preview tab keeps its session in
  // sessionStorage so it stays scoped to that tab: the admin's original tab
  // keeps its own session in localStorage and is still signed in as the admin
  // when the preview tab is closed.
  const candidate = isPortalEmulationTab() ? window.sessionStorage : window.localStorage;
  if (
    typeof candidate.getItem === "function" &&
    typeof candidate.setItem === "function" &&
    typeof candidate.removeItem === "function"
  ) {
    return candidate;
  }

  return createMemoryStorage();
})();

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: resolvedStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
